const DT_Q = [
  // ─── Materials ───
  {paper:'materials',topic:'Materials',q:'Which of the following is a thermosetting polymer?',options:['A. Polypropylene','B. Polyethylene','C. Melamine formaldehyde','D. Acrylic'],answer:'C',explanation:'Thermosetting polymers (like melamine formaldehyde and epoxy resin) set permanently when heated and cannot be reshaped. Thermoplastics can be reheated and reshaped.',memory_hook:'Thermosetting = set for good. Like concrete — once it hardens, it\'s permanent. Thermoset vs thermoplastic: one is forever, one is flexible.'},
  {paper:'materials',topic:'Materials',q:'What is the main property that makes stainless steel suitable for kitchen cutlery?',options:['A. It is very lightweight','B. It is resistant to corrosion','C. It is the cheapest metal','D. It can be easily cast'],answer:'B',explanation:'Stainless steel contains chromium which forms a protective oxide layer, preventing rust and corrosion — ideal for food contact applications.',memory_hook:'Stainless = no stains, no rust. The chromium in stainless steel creates an invisible shield against corrosion. Perfect for anything touching food or water.'},
  {paper:'materials',topic:'Materials',q:'What is a composite material?',options:['A. A material made from a single element','B. A material made from two or more different materials combined to improve properties','C. A naturally occurring material found in the ground','D. A material that can be recycled easily'],answer:'B',explanation:'Composites combine materials to get the best properties of each — for example, carbon fibre reinforced polymer (CFRP) combines strength from fibres with light weight from the matrix.',memory_hook:'Composite = combined. Think of reinforced concrete — concrete (compression strength) + steel rebar (tension strength) = better than either alone.'},
  {paper:'materials',topic:'Materials',q:'Which timber is classified as hardwood?',options:['A. Pine','B. Spruce','C. Oak','D. Balsa'],answer:'C',explanation:'Hardwoods come from deciduous (broad-leaved) trees like oak, mahogany and walnut. Softwoods come from coniferous (cone-bearing) trees like pine and spruce. Balsa is technically a hardwood but unusually soft.',memory_hook:'Hardwood = broad-leaved trees that lose their leaves (deciduous). Oak, ash, beech. Softwood = conifers that keep their needles. Pine, spruce, fir.'},
  {paper:'materials',topic:'Materials',q:'What does the term "ferrous metal" mean?',options:['A. A metal that conducts electricity','B. A metal that contains iron','C. A metal that resists corrosion','D. A metal extracted from seawater'],answer:'B',explanation:'Ferrous metals contain iron (from the Latin "ferrum"). They are generally magnetic and prone to rust, unlike non-ferrous metals such as aluminium and copper.',memory_hook:'Ferrous = iron. Fe is iron on the periodic table (also from "ferrum"). If you can remember Fe = iron, you can always work out what ferrous means.'},
  {paper:'materials',topic:'Materials',q:'What is the main advantage of using aluminium over steel for aircraft bodies?',options:['A. It is stronger than steel','B. It is much lighter for similar strength','C. It is cheaper than steel','D. It is easier to weld'],answer:'B',explanation:'Aluminium has a much lower density than steel but has a good strength-to-weight ratio, making it ideal for aerospace applications where weight must be minimised.',memory_hook:'Aluminium = light AND strong enough. Aircraft need strength without weight. Al is about 1/3 the density of steel, which is why planes aren\'t made of steel.'},

  // ─── Design Process ───
  {paper:'design',topic:'Design Process',q:'What is a design brief?',options:['A. A detailed technical drawing of a product','B. A short statement from a client outlining the design problem to be solved','C. A list of materials needed to make a product','D. A final evaluation of a completed product'],answer:'B',explanation:'A design brief is a statement from the client explaining the problem, context and general requirements — it is the starting point for any design project.',memory_hook:'Brief = brief description of the problem. The client tells you WHAT they want solved; your job is to figure out HOW. It\'s the starting gun for design.'},
  {paper:'design',topic:'Design Process',q:'What is a design specification?',options:['A. A rough sketch of an idea','B. A detailed list of criteria and constraints the final design must meet','C. A photograph of an existing similar product','D. The manufacturing instructions for a product'],answer:'B',explanation:'A design specification translates the brief into measurable criteria (e.g. must weigh less than 200g, must cost under £5, must be waterproof) that the solution must satisfy.',memory_hook:'Specification = specific requirements. It turns the vague brief into measurable targets. SMART criteria — specific, measurable, achievable, realistic, time-bound.'},
  {paper:'design',topic:'Design Process',q:'What is the purpose of a prototype in the design process?',options:['A. To produce the final version of the product for sale','B. To test ideas, identify problems and refine the design before full production','C. To create a detailed cost breakdown','D. To replace the need for technical drawings'],answer:'B',explanation:'Prototypes allow designers to test how well a design works in practice, find flaws, and make improvements before committing to expensive full production.',memory_hook:'Prototype = test run. It\'s cheaper to discover problems on a prototype than after making 10,000 units. Fail fast, learn fast, improve.'},
  {paper:'design',topic:'Design Process',q:'What does anthropometric data refer to in design?',options:['A. Survey data about consumer preferences','B. Measurements of the human body used to ensure products fit users','C. Environmental impact assessments','D. Cost analysis of materials'],answer:'B',explanation:'Anthropometrics is the study of human body measurements. Designers use percentile data (e.g. 5th to 95th percentile) to ensure products fit a range of users.',memory_hook:'Anthropo = human, metric = measurement. Anthropometric data tells you how big humans are — so you design chairs, keyboards and handles that fit real people.'},
  {paper:'design',topic:'Design Process',q:'What is meant by ergonomics in product design?',options:['A. Making a product as cheap as possible','B. Designing products to fit the way people naturally move and use them','C. Using environmentally friendly materials','D. Making products aesthetically attractive'],answer:'B',explanation:'Ergonomics (human factors) focuses on designing products that are comfortable, efficient and safe to use by matching the design to human physical and cognitive capabilities.',memory_hook:'Ergonomics = designing for humans. A chair with good ergonomics supports your back naturally. Bad ergonomics = aching wrists, sore back, user frustration.'},

  // ─── Manufacturing ───
  {paper:'manufacturing',topic:'Manufacturing',q:'What is CAD used for in manufacturing?',options:['A. Calculating the cost of materials','B. Creating precise digital designs and technical drawings on a computer','C. Automatically assembling products','D. Testing the strength of materials'],answer:'B',explanation:'Computer Aided Design (CAD) software allows designers to create detailed 2D and 3D models digitally, which can be tested, modified and sent directly to manufacturing machines.',memory_hook:'CAD = drawing on a computer. Instead of pencil and paper, you design in software. The digital file can go straight to a CNC machine or 3D printer.'},
  {paper:'manufacturing',topic:'Manufacturing',q:'What is the difference between a one-off and batch production?',options:['A. One-off is automated; batch is manual','B. One-off makes a single unique item; batch makes a set quantity of identical items','C. Batch is always higher quality than one-off','D. One-off is cheaper per unit than batch'],answer:'B',explanation:'One-off production makes single unique items (e.g. a bespoke suit). Batch production makes a fixed number of identical items (e.g. 500 school desks), then the line changes to another product.',memory_hook:'One-off = unique. Batch = a specific run of identical items. Like baking: one-off is baking one special cake; batch is baking 24 identical muffins.'},
  {paper:'manufacturing',topic:'Manufacturing',q:'What does CNC stand for and what is it used for?',options:['A. Computer Numerical Control — for automated precision machining','B. Calculated Numerical Cutting — for hand tools','C. Computer Network Centre — for connecting machines','D. Controlled Numerical Construction — for 3D printing'],answer:'A',explanation:'CNC (Computer Numerical Control) machines follow programmed instructions to cut, drill or shape materials with high precision and repeatability, reducing human error.',memory_hook:'CNC = the machine reads the code and does the cutting itself. Give it the CAD file, and it machines the part automatically — precise every time.'},
  {paper:'manufacturing',topic:'Manufacturing',q:'What is a mortise and tenon joint used for?',options:['A. Joining two pieces of metal with heat','B. Joining two pieces of wood at right angles without adhesive','C. Connecting electrical components on a circuit board','D. Joining sheet metal using folded edges'],answer:'B',explanation:'A mortise and tenon joint is a traditional woodworking joint where a rectangular tenon on one piece fits into a corresponding mortise hole in the other, creating a strong right-angle joint.',memory_hook:'Mortise = hole. Tenon = tongue. The tongue goes into the hole. It\'s like a plug and socket for wood — a classic joint used in furniture for centuries.'},

  // ─── Electronics ───
  {paper:'electronics',topic:'Electronics',q:'What is the function of a resistor in a circuit?',options:['A. To store electrical charge','B. To limit or control the flow of electric current','C. To amplify the current','D. To convert electrical energy to light'],answer:'B',explanation:'A resistor opposes the flow of current according to Ohm\'s Law (V = IR). It is used to protect components from excessive current or to set specific voltage levels.',memory_hook:'Resistor = resists current. Like a narrow section in a pipe slowing water flow, a resistor slows down electrical current. V = IR — bigger R means smaller I.'},
  {paper:'electronics',topic:'Electronics',q:'What does an LED stand for and what does it do?',options:['A. Low Energy Device — stores charge','B. Light Emitting Diode — produces light when current flows through it','C. Linear Electronic Detector — measures voltage','D. Liquid Electronic Display — shows images'],answer:'B',explanation:'An LED (Light Emitting Diode) emits light when current flows through it in the correct direction. It is highly energy-efficient compared to traditional bulbs.',memory_hook:'LED = Light Emitting Diode. Di = two terminals (anode + cathode). Current must flow the right way (forward biased) to emit light. LEDs are extremely efficient.'},
  {paper:'electronics',topic:'Electronics',q:'What does a capacitor do in a circuit?',options:['A. Allows current to flow in one direction only','B. Stores and releases electrical charge','C. Converts AC to DC','D. Amplifies weak signals'],answer:'B',explanation:'A capacitor stores electrical charge when voltage is applied and releases it when needed. It is used for smoothing power supplies, timing circuits and filtering.',memory_hook:'Capacitor = stores charge like a tiny rechargeable battery. It charges up, then releases its stored energy. Used in camera flashes — charge up, then flash!'},
  {paper:'electronics',topic:'Electronics',q:'In a series circuit with two resistors of 4Ω and 6Ω, what is the total resistance?',options:['A. 2Ω','B. 2.4Ω','C. 10Ω','D. 24Ω'],answer:'C',explanation:'In a series circuit, resistances add together: R_total = R1 + R2 = 4 + 6 = 10Ω.',memory_hook:'Series = add the resistances. R_total = R1 + R2 + ... Simple addition. In parallel it\'s trickier (1/R_total = 1/R1 + 1/R2), but series is just adding.'},
];
