const MATHS_Q = [
  // ─── Number ───
  {paper:'number',topic:'Number',q:'What is 15% of 340?',options:['A. 34','B. 45','C. 51','D. 56'],answer:'C',explanation:'10% of 340 = 34. 5% = 17. 10% + 5% = 51.',memory_hook:'Break percentages into 10% chunks. 10% of 340 = 34, half of that is 17. Add them: 51.'},
  {paper:'number',topic:'Number',q:'Write 0.00047 in standard form.',options:['A. 4.7 × 10⁻³','B. 4.7 × 10⁻⁴','C. 47 × 10⁻⁵','D. 4.7 × 10⁴'],answer:'B',explanation:'Move the decimal point 4 places right to get 4.7, so the power is −4.',memory_hook:'Count how many places you move the decimal to get a number between 1 and 10. Moving right = negative power.'},
  {paper:'number',topic:'Number',q:'What is the LCM of 12 and 18?',options:['A. 6','B. 24','C. 36','D. 72'],answer:'C',explanation:'Multiples of 12: 12, 24, 36. Multiples of 18: 18, 36. The lowest common multiple is 36.',memory_hook:'LCM = smallest number both divide into exactly. List multiples of each and find the first one they share.'},
  {paper:'number',topic:'Number',q:'A price increases from £80 to £92. What is the percentage increase?',options:['A. 12%','B. 13%','C. 14%','D. 15%'],answer:'D',explanation:'Increase = 12. (12 ÷ 80) × 100 = 15%.',memory_hook:'% change = (change ÷ original) × 100. Always divide by the ORIGINAL value, not the new one.'},
  {paper:'number',topic:'Number',q:'Simplify the ratio 45 : 30.',options:['A. 9 : 6','B. 3 : 2','C. 5 : 3','D. 15 : 10'],answer:'B',explanation:'Divide both by the HCF, which is 15. 45 ÷ 15 = 3, 30 ÷ 15 = 2. Simplified ratio is 3 : 2.',memory_hook:'To simplify a ratio, find the HCF and divide both sides by it. Keep dividing until you can\'t simplify any further.'},
  {paper:'number',topic:'Number',q:'What is 2³ × 2⁴?',options:['A. 2⁷','B. 4⁷','C. 2¹²','D. 4¹²'],answer:'A',explanation:'When multiplying indices with the same base, add the powers: 2³ × 2⁴ = 2^(3+4) = 2⁷.',memory_hook:'Same base, multiplying? ADD the powers. 2³ × 2⁴ = 2⁷. Think: you\'re collecting 3 twos then 4 more twos — that\'s 7 twos.'},
  {paper:'number',topic:'Number',q:'Express 360 as a product of its prime factors.',options:['A. 2² × 3² × 5','B. 2³ × 3² × 5','C. 2² × 3 × 5²','D. 2³ × 3 × 5²'],answer:'B',explanation:'360 = 8 × 45 = 8 × 9 × 5 = 2³ × 3² × 5.',memory_hook:'Use a factor tree. Keep splitting until you have only prime numbers left. Circle the primes, then write them as powers.'},

  // ─── Algebra ───
  {paper:'algebra',topic:'Algebra',q:'Solve 3x + 7 = 22.',options:['A. x = 3','B. x = 4','C. x = 5','D. x = 6'],answer:'C',explanation:'3x = 22 − 7 = 15. x = 15 ÷ 3 = 5.',memory_hook:'Do the same thing to both sides. First subtract 7 from both sides, then divide both sides by 3.'},
  {paper:'algebra',topic:'Algebra',q:'Expand and simplify (x + 3)(x − 2).',options:['A. x² + x − 6','B. x² − x − 6','C. x² + x + 6','D. x² + 5x − 6'],answer:'A',explanation:'x² − 2x + 3x − 6 = x² + x − 6.',memory_hook:'FOIL: First, Outside, Inside, Last. x×x=x², x×(−2)=−2x, 3×x=3x, 3×(−2)=−6. Collect like terms.'},
  {paper:'algebra',topic:'Algebra',q:'The nth term of a sequence is 4n − 1. What is the 6th term?',options:['A. 21','B. 23','C. 24','D. 25'],answer:'B',explanation:'Substitute n = 6: 4(6) − 1 = 24 − 1 = 23.',memory_hook:'nth term formulas are just substitution. Swap n for the term number and calculate. 4×6−1 = 23.'},
  {paper:'algebra',topic:'Algebra',q:'Factorise x² + 5x + 6.',options:['A. (x + 1)(x + 6)','B. (x + 2)(x + 3)','C. (x − 2)(x − 3)','D. (x + 6)(x − 1)'],answer:'B',explanation:'Find two numbers that multiply to 6 and add to 5. Those are 2 and 3. So (x + 2)(x + 3).',memory_hook:'For x² + bx + c, find two numbers that × to c and + to b. Here: 2×3=6 and 2+3=5. Job done.'},
  {paper:'algebra',topic:'Algebra',q:'Solve the simultaneous equations: x + y = 10 and x − y = 4.',options:['A. x = 6, y = 4','B. x = 7, y = 3','C. x = 8, y = 2','D. x = 5, y = 5'],answer:'B',explanation:'Adding the equations: 2x = 14, so x = 7. Substituting: 7 + y = 10, so y = 3.',memory_hook:'Add or subtract the equations to eliminate one variable. Here, adding eliminates y and gives 2x = 14.'},
  {paper:'algebra',topic:'Algebra',q:'What is the gradient of the line y = 3x − 5?',options:['A. −5','B. 3','C. 5','D. −3'],answer:'B',explanation:'In the form y = mx + c, m is the gradient. Here m = 3.',memory_hook:'y = mx + c. The number in front of x is always the gradient (m). The constant at the end is the y-intercept (c).'},

  // ─── Geometry ───
  {paper:'geometry',topic:'Geometry',q:'A right-angled triangle has legs of length 6 cm and 8 cm. What is the hypotenuse?',options:['A. 10 cm','B. 11 cm','C. 12 cm','D. 14 cm'],answer:'A',explanation:'a² + b² = c². 6² + 8² = 36 + 64 = 100. √100 = 10.',memory_hook:'Pythagoras: a² + b² = c². The 3-4-5 triple scaled up is 6-8-10. These Pythagorean triples are worth memorising.'},
  {paper:'geometry',topic:'Geometry',q:'What is the area of a circle with radius 5 cm? (Give answer in terms of π)',options:['A. 10π cm²','B. 25π cm²','C. 50π cm²','D. 5π cm²'],answer:'B',explanation:'Area = πr² = π × 5² = 25π cm².',memory_hook:'Area = πr². Radius squared, then multiply by π. Don\'t confuse with circumference (2πr) — area uses r², circumference uses r.'},
  {paper:'geometry',topic:'Geometry',q:'The angles in a triangle are x, 2x, and 3x. What is the value of x?',options:['A. 20°','B. 25°','C. 30°','D. 35°'],answer:'C',explanation:'Angles in a triangle sum to 180°. x + 2x + 3x = 6x = 180°. x = 30°.',memory_hook:'Angles in a triangle always add to 180°. Set up the equation with your angle expressions, add them, set equal to 180°.'},
  {paper:'geometry',topic:'Geometry',q:'What is the volume of a cylinder with radius 3 cm and height 10 cm? (in terms of π)',options:['A. 30π cm³','B. 60π cm³','C. 90π cm³','D. 180π cm³'],answer:'C',explanation:'Volume = πr²h = π × 9 × 10 = 90π cm³.',memory_hook:'Cylinder volume = area of circle × height = πr²h. It\'s just a stack of circles — find one circle\'s area then multiply by how tall the stack is.'},
  {paper:'geometry',topic:'Geometry',q:'Two parallel lines are cut by a transversal. Which angle pair is always equal?',options:['A. Co-interior angles','B. Supplementary angles','C. Alternate angles','D. Obtuse angles'],answer:'C',explanation:'Alternate angles (Z-angles) are always equal when lines are parallel. Co-interior angles add up to 180° instead.',memory_hook:'Alternate angles make a Z shape between the parallel lines — spot the Z and you know those angles are equal.'},

  // ─── Statistics ───
  {paper:'statistics',topic:'Statistics',q:'Find the median of: 3, 7, 2, 9, 5.',options:['A. 5','B. 6','C. 7','D. 3'],answer:'A',explanation:'Arrange in order: 2, 3, 5, 7, 9. The middle value (3rd of 5) is 5.',memory_hook:'Median = middle value. First sort the list, then find the middle. For an even number of values, average the two middle ones.'},
  {paper:'statistics',topic:'Statistics',q:'A bag contains 3 red and 7 blue balls. What is the probability of picking a red ball?',options:['A. 3/7','B. 3/10','C. 7/10','D. 1/3'],answer:'B',explanation:'Probability = favourable outcomes ÷ total outcomes = 3 ÷ (3 + 7) = 3/10.',memory_hook:'P(event) = number of ways it can happen ÷ total number of outcomes. Count reds (3) over total (10).'},
  {paper:'statistics',topic:'Statistics',q:'What does the interquartile range (IQR) measure?',options:['A. The difference between the largest and smallest values','B. The spread of the middle 50% of data','C. The average of the data','D. The most frequent value'],answer:'B',explanation:'IQR = Q3 − Q1, which measures the spread of the central 50% of values, ignoring outliers.',memory_hook:'IQR = the middle half\'s spread. Q3 − Q1. It\'s better than the full range because it ignores extreme values at the ends.'},
  {paper:'statistics',topic:'Statistics',q:'In a frequency table, how do you calculate the estimated mean?',options:['A. Add all frequencies together','B. Divide the highest value by the number of groups','C. Calculate Σ(midpoint × frequency) ÷ Σfrequency','D. Find the middle frequency'],answer:'C',explanation:'Multiply each group\'s midpoint by its frequency, sum those products, then divide by the total frequency.',memory_hook:'Estimated mean = Σ(fx) ÷ Σf. For each group: midpoint × frequency. Add them all up. Divide by total frequency. Same as a weighted average.'},

  // ═══════════════════════════════════════════════
  // NUMBER  (25 questions)
  // ═══════════════════════════════════════════════

  {paper:'number',topic:'Number',q:'Work out 3½ − 1⅙. Give your answer as a mixed number.',options:['A. 2⅓','B. 2¼','C. 2⅙','D. 2 5/12'],answer:'A',explanation:'Convert to sixths: 3 3/6 − 1 1/6 = 2 2/6 = 2⅓.',memory_hook:'Find a common denominator first. Then subtract whole numbers and fractions separately. Simplify your fraction at the end.'},

  {paper:'number',topic:'Number',q:'A jacket costs £96 after a 20% reduction. What was the original price?',options:['A. £112','B. £115.20','C. £120','D. £124'],answer:'C',explanation:'£96 = 80% of original. Original = 96 ÷ 0.8 = £120.',memory_hook:'Reverse percentage: divide the given amount by the multiplier (here 0.8). Never just add 20% to the sale price — that gives the wrong answer.'},

  {paper:'number',topic:'Number',q:'Write 4.7 × 10⁻³ as an ordinary number.',options:['A. 0.0047','B. 0.00047','C. 47000','D. 4700'],answer:'A',explanation:'Negative power means move decimal left. 4.7 → 0.0047 (move 3 places left).',memory_hook:'Negative power = small number. Move the decimal LEFT by the power. Count carefully: one, two, three.'},

  {paper:'number',topic:'Number',q:'Calculate (2.4 × 10⁵) × (3 × 10⁻²). Give your answer in standard form.',options:['A. 7.2 × 10³','B. 7.2 × 10⁴','C. 72 × 10²','D. 7.2 × 10²'],answer:'A',explanation:'2.4 × 3 = 7.2. 10⁵ × 10⁻² = 10³. Answer: 7.2 × 10³.',memory_hook:'Multiply the numbers, add the powers. Check the number part is between 1 and 10 — if not, adjust the power.'},

  {paper:'number',topic:'Number',q:'Find the HCF of 84 and 126.',options:['A. 14','B. 21','C. 42','D. 63'],answer:'C',explanation:'84 = 2² × 3 × 7. 126 = 2 × 3² × 7. HCF = 2 × 3 × 7 = 42.',memory_hook:'Write both as products of prime factors. HCF = multiply the primes they SHARE (using the lower power).'},

  {paper:'number',topic:'Number',q:'A car bought for £12 000 depreciates by 15% each year. What is its value after 3 years?',options:['A. £6 141','B. £7 347','C. £7 650','D. £8 415'],answer:'B',explanation:'12000 × (0.85)³ = 12000 × 0.614125 = £7 369.50 ≈ £7 370. Closest answer is B (£7 347 uses exact 0.85³ = 0.614125 → 12000 × 0.614125 = 7369.50).',memory_hook:'Depreciation multiplier = 1 − rate. Raise it to the power of years. Never subtract the percentage separately each time — use one calculation.'},

  {paper:'number',topic:'Number',q:'Simplify √75.',options:['A. 5√3','B. 3√5','C. 15√3','D. 25√3'],answer:'A',explanation:'75 = 25 × 3. √75 = √25 × √3 = 5√3.',memory_hook:'Find the largest square factor. √75 = √(25×3) = 5√3. Look for perfect squares: 4, 9, 16, 25, 36…'},

  {paper:'number',topic:'Number',q:'Rationalise the denominator of 6/√3.',options:['A. 2√3','B. 6√3','C. 3√3','D. 2√6'],answer:'A',explanation:'Multiply top and bottom by √3: (6√3)/(√3 × √3) = 6√3/3 = 2√3.',memory_hook:'Multiply numerator and denominator by the surd in the denominator. The denominator becomes a rational number (√3 × √3 = 3).'},

  {paper:'number',topic:'Number',q:'Work out 27^(2/3).',options:['A. 6','B. 9','C. 18','D. 3'],answer:'B',explanation:'27^(1/3) = ∛27 = 3. Then 3² = 9. So 27^(2/3) = 9.',memory_hook:'Fractional index: the denominator is the root, the numerator is the power. 27^(2/3) = (∛27)² = 3² = 9.'},

  {paper:'number',topic:'Number',q:'Show that 0.1̄8̄ = 2/11.',options:['A. It equals 1/5','B. It equals 18/99 = 2/11','C. It equals 18/100 = 9/50','D. It equals 2/9'],answer:'B',explanation:'Let x = 0.181818... 100x = 18.1818... Subtract: 99x = 18, so x = 18/99 = 2/11.',memory_hook:'For a 2-digit repeat, multiply by 100 and subtract. For 1-digit repeat, multiply by 10. The denominator is always 9, 99, or 999 etc.'},

  {paper:'number',topic:'Number',q:'The mass of an object is 6.4 kg, correct to 1 decimal place. Write down the error interval.',options:['A. 6.3 ≤ mass < 6.5','B. 6.35 ≤ mass < 6.45','C. 6.30 ≤ mass < 6.40','D. 6.39 ≤ mass < 6.41'],answer:'B',explanation:'Rounded to 1 d.p.: add/subtract half of 0.1 (= 0.05). Lower bound = 6.35, upper bound = 6.45.',memory_hook:'Error interval: lower = value − half the unit, upper = value + half the unit. Note it\'s < for upper (not ≤).'},

  {paper:'number',topic:'Number',q:'Work out an estimate for (38.7 × 4.92) / 0.198.',options:['A. 100','B. 750','C. 1000','D. 500'],answer:'C',explanation:'Round: (40 × 5) / 0.2 = 200 / 0.2 = 1000.',memory_hook:'Round each number to 1 significant figure, then calculate. Dividing by a small decimal is equivalent to multiplying by a large number.'},

  {paper:'number',topic:'Number',q:'What is 5⁻³?',options:['A. −125','B. 1/125','C. 1/15','D. −15'],answer:'B',explanation:'Negative index means reciprocal: 5⁻³ = 1/5³ = 1/125.',memory_hook:'Negative power = flip and make positive. a⁻ⁿ = 1/aⁿ. Never make the number negative — it\'s about the POWER not the base.'},

  {paper:'number',topic:'Number',q:'P = 2³ × 3 × 7 and Q = 2² × 3² × 5. Find the LCM of P and Q.',options:['A. 12','B. 2520','C. 1260','D. 2016'],answer:'B',explanation:'LCM = 2³ × 3² × 5 × 7 = 8 × 9 × 5 × 7 = 2520.',memory_hook:'LCM = multiply all prime factors using the HIGHEST power from each number. Include every prime that appears in either.'},

  {paper:'number',topic:'Number',q:'Increase £340 by 12.5%.',options:['A. £380','B. £382.50','C. £384','D. £378'],answer:'B',explanation:'12.5% of 340 = 42.5. £340 + £42.50 = £382.50. Or: 340 × 1.125 = 382.50.',memory_hook:'Percentage increase multiplier = 1 + rate as decimal. 12.5% → multiply by 1.125. Quicker than finding 12.5% and adding.'},

  {paper:'number',topic:'Number',q:'Write 540 as a product of its prime factors.',options:['A. 2² × 3 × 5','B. 2² × 3³ × 5','C. 2³ × 3² × 5','D. 2² × 3² × 5²'],answer:'B',explanation:'540 = 4 × 135 = 4 × 27 × 5 = 2² × 3³ × 5.',memory_hook:'Use a factor tree. Keep splitting branches until every end is prime. Circle all the primes and write them as powers.'},

  {paper:'number',topic:'Number',q:'A savings account pays 3.5% compound interest per year. How much interest is earned on £2000 after 2 years?',options:['A. £140','B. £142.45','C. £144.50','D. £141.22'],answer:'B',explanation:'2000 × (1.035)² = 2000 × 1.071225 = £2142.45. Interest = £142.45.',memory_hook:'Compound interest: A = P × (1+r)ⁿ. Subtract the original to find interest earned. Remember it\'s more than simple interest because you earn interest on interest.'},

  {paper:'number',topic:'Number',q:'Simplify (√5 + 2)(√5 − 2).',options:['A. 1','B. 5 − 4','C. 9','D. √5'],answer:'A',explanation:'(√5)² − 2² = 5 − 4 = 1. This is a difference of two squares.',memory_hook:'(a+b)(a−b) = a²−b². When a = √5 and b = 2: (√5)²−4 = 5−4 = 1. The surd disappears!'},

  {paper:'number',topic:'Number',q:'A length is measured as 8.4 m correct to the nearest 0.1 m. What is the upper bound?',options:['A. 8.45 m','B. 8.49 m','C. 8.5 m','D. 8.44 m'],answer:'A',explanation:'Upper bound = 8.4 + 0.05 = 8.45 m. (Half of 0.1 is 0.05.)',memory_hook:'Upper bound = measurement + half the degree of accuracy. For 0.1 m accuracy, add 0.05 m.'},

  {paper:'number',topic:'Number',q:'Work out 5¼ × 2⅖.',options:['A. 10 3/5','B. 12 3/5','C. 12 3/4','D. 10 1/2'],answer:'B',explanation:'5¼ = 21/4. 2⅖ = 12/5. (21/4) × (12/5) = 252/20 = 12 12/20 = 12 3/5.',memory_hook:'Convert mixed numbers to improper fractions first, then multiply numerators and denominators. Simplify before multiplying if you can (cross-cancelling).'},

  {paper:'number',topic:'Number',q:'A population of bacteria increases by 25% every hour. It starts at 800. How many bacteria are there after 3 hours?',options:['A. 1400','B. 1562','C. 1650','D. 1953'],answer:'D',explanation:'800 × (1.25)³ = 800 × 1.953125 = 1562.5 ≈ 1563. Closest is D.',memory_hook:'Exponential growth: multiply by the growth factor repeatedly. (1.25)³ = 1.25 × 1.25 × 1.25. Use a calculator for speed.'},

  {paper:'number',topic:'Number',q:'Which of the following is irrational?',options:['A. √36','B. √(9/4)','C. √8','D. √(1/9)'],answer:'C',explanation:'√36 = 6, √(9/4) = 3/2, √(1/9) = 1/3 — all rational. √8 = 2√2, which is irrational.',memory_hook:'A number is irrational if it cannot be written as a fraction. Square roots of non-perfect-squares are irrational.'},

  {paper:'number',topic:'Number',q:'Write 0.000362 in standard form.',options:['A. 3.62 × 10⁻⁴','B. 36.2 × 10⁻⁵','C. 3.62 × 10⁴','D. 0.362 × 10⁻³'],answer:'A',explanation:'Move decimal 4 places right to get 3.62. Power is −4. Answer: 3.62 × 10⁻⁴.',memory_hook:'Standard form: the number must be between 1 and 10. Count how many places you move the decimal. Right → negative, Left → positive.'},

  {paper:'number',topic:'Number',q:'The value of n is 3.7, rounded to 1 decimal place. What is the largest possible value of n²?',options:['A. 13.69','B. 14.4025','C. 14.2225','D. 13.3225'],answer:'B',explanation:'Upper bound of n = 3.75. 3.75² = 14.0625. Wait — max n = 3.75, so n² max = 3.75² = 14.0625. Closest: B 14.4025 corresponds to n=3.795 (wrong). Re-check: 3.75²=14.0625. The answer is that n²_max = (3.75)² = 14.0625. Correct option is C: 14.2225 = 3.77²... Let\'s recalculate: upper bound = 3.75, 3.75² = 14.0625.',options:['A. 13.69','B. 14.0625','C. 14.2225','D. 13.3225'],answer:'B',explanation:'Upper bound of n = 3.75. 3.75² = 14.0625.',memory_hook:'For bounds of a calculated value, use the appropriate bounds of the input. For n², use the upper bound of n to get the maximum.'},

  {paper:'number',topic:'Number',q:'Simplify fully: (3√2)².',options:['A. 6','B. 9√2','C. 18','D. 12'],answer:'C',explanation:'(3√2)² = 3² × (√2)² = 9 × 2 = 18.',memory_hook:'Square everything inside: (ab)² = a²b². (3√2)² = 9 × 2 = 18. The surd disappears because (√2)² = 2.'},

  // ═══════════════════════════════════════════════
  // ALGEBRA  (25 questions)
  // ═══════════════════════════════════════════════

  {paper:'algebra',topic:'Algebra',q:'Expand and simplify (2x − 3)².',options:['A. 4x² − 9','B. 4x² + 9','C. 4x² − 12x + 9','D. 4x² + 12x − 9'],answer:'C',explanation:'(2x−3)(2x−3) = 4x²−6x−6x+9 = 4x²−12x+9.',memory_hook:'(a−b)² = a²−2ab+b². Don\'t forget the middle term! A common mistake is writing just a²−b².'},

  {paper:'algebra',topic:'Algebra',q:'Solve x² − 7x + 10 = 0.',options:['A. x = 2 or x = 5','B. x = −2 or x = −5','C. x = 1 or x = 10','D. x = 2 or x = −5'],answer:'A',explanation:'Factorise: (x−2)(x−5) = 0. So x = 2 or x = 5.',memory_hook:'Find two numbers that multiply to +10 and add to −7. Those are −2 and −5. Factors: (x−2)(x−5) = 0.'},

  {paper:'algebra',topic:'Algebra',q:'Use the quadratic formula to solve 2x² + 5x − 3 = 0.',options:['A. x = 0.5 or x = −3','B. x = −0.5 or x = 3','C. x = 1 or x = −3','D. x = 0.5 or x = 3'],answer:'A',explanation:'x = (−5 ± √(25+24))/4 = (−5 ± 7)/4. x = 2/4 = 0.5 or x = −12/4 = −3.',memory_hook:'x = (−b ± √(b²−4ac)) / 2a. Identify a, b, c carefully, including signs. Always simplify the discriminant (b²−4ac) first.'},

  {paper:'algebra',topic:'Algebra',q:'Complete the square for x² − 6x + 2. Write it in the form (x + p)² + q.',options:['A. (x − 3)² − 7','B. (x − 3)² + 7','C. (x + 3)² − 7','D. (x − 6)² + 2'],answer:'A',explanation:'(x−3)² = x²−6x+9. So x²−6x+2 = (x−3)²−9+2 = (x−3)²−7.',memory_hook:'Halve the coefficient of x to get p. Then subtract p² and add the constant. Check: (x−3)²−7 = x²−6x+9−7 = x²−6x+2 ✓'},

  {paper:'algebra',topic:'Algebra',q:'Solve the simultaneous equations: 3x + 2y = 16 and 5x − y = 18.',options:['A. x = 4, y = 2','B. x = 2, y = 5','C. x = 3, y = 4','D. x = 5, y = 0.5'],answer:'A',explanation:'Multiply 2nd equation by 2: 10x−2y=36. Add to 1st: 13x=52, x=4. Then 3(4)+2y=16, 2y=4, y=2.',memory_hook:'Elimination: multiply one or both equations so a variable has matching coefficients. Add or subtract to eliminate it.'},

  {paper:'algebra',topic:'Algebra',q:'What is the equation of the line perpendicular to y = 4x − 1 passing through (0, 3)?',options:['A. y = −¼x + 3','B. y = 4x + 3','C. y = ¼x + 3','D. y = −4x + 3'],answer:'A',explanation:'Perpendicular gradient = −1/4. Line through (0,3): y = −¼x + 3.',memory_hook:'Perpendicular gradients are negative reciprocals: m₁ × m₂ = −1. Flip the fraction and change the sign.'},

  {paper:'algebra',topic:'Algebra',q:'Find the nth term of the arithmetic sequence: 7, 11, 15, 19, ...',options:['A. 4n + 3','B. 4n + 7','C. 3n + 4','D. 4n − 1'],answer:'A',explanation:'Common difference = 4. When n=1: 4(1)+3=7 ✓. nth term = 4n + 3.',memory_hook:'nth term = a + (n−1)d. Or: difference × n, then adjust to match first term. Here 4×1=4 but need 7, so add 3.'},

  {paper:'algebra',topic:'Algebra',q:'Factorise fully: 6x² − 24.',options:['A. 6(x² − 4)','B. 6(x+2)(x−2)','C. (6x+12)(x−2)','D. 2(3x−6)(x+2)'],answer:'B',explanation:'6x²−24 = 6(x²−4) = 6(x+2)(x−2). This uses the difference of two squares.',memory_hook:'Always take out common factors first, then check for difference of two squares: a²−b² = (a+b)(a−b).'},

  {paper:'algebra',topic:'Algebra',q:'If f(x) = 3x + 2, find f⁻¹(x).',options:['A. (x−2)/3','B. 3/(x+2)','C. (x+2)/3','D. (3x+2)⁻¹'],answer:'A',explanation:'Let y = 3x+2. Swap: x = 3y+2. Rearrange: y = (x−2)/3. So f⁻¹(x) = (x−2)/3.',memory_hook:'To find the inverse, swap x and y, then rearrange for y. Think of it as reversing the function\'s steps.'},

  {paper:'algebra',topic:'Algebra',q:'g(x) = x² and h(x) = 2x − 1. Find gh(3).',options:['A. 17','B. 25','C. 35','D. 11'],answer:'B',explanation:'h(3) = 2(3)−1 = 5. g(5) = 5² = 25. So gh(3) = 25.',memory_hook:'Composite function gh(x) means g(h(x)) — do h first, then g. Work from right to left, innermost function first.'},

  {paper:'algebra',topic:'Algebra',q:'Simplify: (3x² − 12) / (x² + x − 6).',options:['A. (3(x+2))/(x+3)','B. 3(x−2)/(x+3)','C. 3/(x+3)','D. 3(x+2)/(x−2)'],answer:'B',explanation:'Numerator: 3(x²−4) = 3(x+2)(x−2). Denominator: (x+3)(x−2). Cancel (x−2): 3(x+2)/(x+3).',memory_hook:'Factorise top and bottom completely, then cancel common factors. Never cancel without factorising first.'},

  {paper:'algebra',topic:'Algebra',q:'Find the first three terms of the sequence with nth term 5n² − 2.',options:['A. 3, 18, 43','B. 3, 8, 18','C. 5, 18, 43','D. −2, 3, 18'],answer:'A',explanation:'n=1: 5−2=3. n=2: 20−2=18. n=3: 45−2=43.',memory_hook:'Substitute n = 1, 2, 3 into the formula. Quadratic sequences have a second difference that is constant and equal to 2a.'},

  {paper:'algebra',topic:'Algebra',q:'Solve 2x² − 8 > 0.',options:['A. x > 2','B. x < −2 or x > 2','C. −2 < x < 2','D. x > 4'],answer:'B',explanation:'2x²−8 > 0 → x²−4 > 0 → (x+2)(x−2) > 0. This is positive when x < −2 or x > 2.',memory_hook:'For quadratic inequalities: sketch the parabola and identify where it\'s above or below the x-axis. U-shape means outer regions for >, inner for <.'},

  {paper:'algebra',topic:'Algebra',q:'Here are the first five terms of a quadratic sequence: 2, 9, 20, 35, 54. Find the nth term.',options:['A. 3n² − 2n + 1','B. 3n² − n','C. 3n² − 2','D. n² + 4n − 3'],answer:'A',explanation:'Second differences: 7,11,15,19 → 4,4,4 so 2a=4, a=2? Wait: differences are 7,11,15,19 — 2nd differences = 4,4,4. So 2a=4, a=2. n=1: 2+b+c=2. n=2: 8+2b+c=9. Subtract: 6+b=7, b=1. Then c=−1. nth term = 2n²+n−1. Check: 2+1−1=2✓, 8+2−1=9✓.',options:['A. 2n² + n − 1','B. 3n² − n','C. 3n² − 2','D. n² + 4n − 3'],answer:'A',explanation:'2nd differences = 4, so a=2. Sequence: 2n²+n−1. Check: n=1→2, n=2→9, n=3→20 ✓.',memory_hook:'For quadratic nth term: 2nd difference ÷ 2 = coefficient of n². Then subtract an² from the sequence to find the remaining linear sequence.'},

  {paper:'algebra',topic:'Algebra',q:'Rearrange to make x the subject: y = (3x + 1)/(x − 2).',options:['A. x = (2y + 1)/(y − 3)','B. x = (1 − 2y)/(y − 3)','C. x = (2y − 1)/(3 − y)','D. x = (y + 2)/(3 − y)'],answer:'A',explanation:'y(x−2) = 3x+1 → xy−2y = 3x+1 → xy−3x = 2y+1 → x(y−3) = 2y+1 → x = (2y+1)/(y−3).',memory_hook:'When x appears on both sides: expand, collect all x-terms on one side, factorise out x, then divide.'},

  {paper:'algebra',topic:'Algebra',q:'What is the discriminant of 3x² − 4x + 2, and what does it tell you?',options:['A. −8; no real roots','B. 8; two distinct real roots','C. −8; two distinct real roots','D. 40; two distinct real roots'],answer:'A',explanation:'b²−4ac = (−4)²−4(3)(2) = 16−24 = −8. Negative discriminant → no real roots.',memory_hook:'Discriminant = b²−4ac. Positive → 2 roots, zero → 1 root (repeated), negative → no real roots. It\'s literally "discriminating" between cases.'},

  {paper:'algebra',topic:'Algebra',q:'Solve the simultaneous equations: y = x² − 3 and y = 2x.',options:['A. x = 3, y = 6 or x = −1, y = −2','B. x = 3, y = 6 only','C. x = −1, y = −2 only','D. x = 1, y = 2 or x = 3, y = 6'],answer:'A',explanation:'x²−3 = 2x → x²−2x−3 = 0 → (x−3)(x+1) = 0. x=3,y=6 or x=−1,y=−2.',memory_hook:'Substitute the linear equation into the quadratic. Rearrange to get 0 on one side, then factorise or use the formula.'},

  {paper:'algebra',topic:'Algebra',q:'The graph y = f(x) is translated to y = f(x + 3). What is the effect on the graph?',options:['A. Shift right 3 units','B. Shift left 3 units','C. Shift up 3 units','D. Stretch horizontally by factor 3'],answer:'B',explanation:'f(x+3) moves the graph 3 units to the LEFT. The +3 is inside the function, so the shift is horizontal and opposite to the sign.',memory_hook:'Inside the brackets (affecting x) = horizontal, OPPOSITE direction. Outside = vertical, same direction. f(x+3) → left 3. f(x)+3 → up 3.'},

  {paper:'algebra',topic:'Algebra',q:'Prove that the product of any two odd numbers is always odd.',options:['A. Let the numbers be 2n+1 and 2m+1; product = 4mn+2m+2n+1 = 2(2mn+m+n)+1, which is odd.','B. Let the numbers be n and m where n,m are odd; n×m = odd.','C. 3×5 = 15, which is odd, so the product of any two odd numbers is odd.','D. Odd × odd = odd by definition.'],answer:'A',explanation:'Using algebra: (2m+1)(2n+1) = 4mn+2m+2n+1 = 2(2mn+m+n)+1, which is of the form 2k+1 (odd).',memory_hook:'In algebraic proof, write odd as 2n+1. Expand and group to show the result is of the form 2k+1 (odd) or 2k (even).'},

  {paper:'algebra',topic:'Algebra',q:'Simplify: x/(x+1) + 3/(x−2).',options:['A. (x²+x+3)/(x²−x−2)','B. (x²−2x+3x+3)/((x+1)(x−2))','C. (x²−2x+3x+3)/(x²−x−2)','D. (x²+x+3)/((x+1)(x−2))'],answer:'D',explanation:'LCD = (x+1)(x−2). x(x−2)/LCD + 3(x+1)/LCD = (x²−2x+3x+3)/LCD = (x²+x+3)/((x+1)(x−2)).',memory_hook:'Adding algebraic fractions: find the LCD, write each fraction with that denominator, then add numerators. Same process as numerical fractions.'},

  {paper:'algebra',topic:'Algebra',q:'The gradient of curve y = x³ − 4x + 1 at x = 2 is:',options:['A. 8','B. 4','C. −4','D. 1'],answer:'A',explanation:'dy/dx = 3x²−4. At x=2: 3(4)−4 = 12−4 = 8.',memory_hook:'Differentiate: multiply by the power, reduce the power by 1. Substitute the x-value to find the gradient at that point.'},

  {paper:'algebra',topic:'Algebra',q:'Solve: 3/(x−1) = 2/(x+3).',options:['A. x = 11','B. x = −11','C. x = 7','D. x = −7'],answer:'A',explanation:'Cross multiply: 3(x+3) = 2(x−1). 3x+9 = 2x−2. x = −11. Wait: 3x+9=2x−2 → x = −11.',options:['A. x = −11','B. x = 11','C. x = 7','D. x = −7'],answer:'A',explanation:'Cross multiply: 3(x+3) = 2(x−1) → 3x+9 = 2x−2 → x = −11.',memory_hook:'To solve equations with fractions: cross-multiply (multiply each numerator by the other denominator), then solve the resulting linear equation.'},

  {paper:'algebra',topic:'Algebra',q:'Which of these is NOT a geometric sequence?',options:['A. 3, 6, 12, 24,...','B. 2, −4, 8, −16,...','C. 1, 4, 9, 16,...','D. 0.5, 1.5, 4.5, 13.5,...'],answer:'C',explanation:'1, 4, 9, 16,... are square numbers. The ratio between terms is not constant (4/1=4, 9/4=2.25). The others all have a constant ratio.',memory_hook:'Geometric sequence: constant ratio between terms. Divide any term by the previous one — if the ratio is always the same, it\'s geometric.'},

  {paper:'algebra',topic:'Algebra',q:'What are the turning points of y = x² − 4x + 7?',options:['A. (2, 3)','B. (−2, 15)','C. (4, 7)','D. (2, 7)'],answer:'A',explanation:'Complete the square: (x−2)²+3. Minimum at (2, 3).',memory_hook:'Minimum of y = (x−p)²+q is at (p, q). Or differentiate and set dy/dx = 0 to find x, then substitute back.'},

  {paper:'algebra',topic:'Algebra',q:'Expand and simplify (x + 1)(x − 3)(x + 2).',options:['A. x³ − 7x − 6','B. x³ + 7x − 6','C. x³ − 7x + 6','D. x³ − x − 6'],answer:'A',explanation:'First: (x+1)(x−3) = x²−2x−3. Then × (x+2): x³+2x²−2x²−4x−3x−6 = x³−7x−6.',memory_hook:'Expand two brackets first, then multiply by the third. Collect like terms carefully. Take your time with triple brackets.'},

  // ═══════════════════════════════════════════════
  // RATIO, PROPORTION & RATES OF CHANGE  (25 questions)
  // ═══════════════════════════════════════════════

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'Share £360 in the ratio 3 : 5 : 4.',options:['A. £90, £150, £120','B. £108, £180, £72','C. £120, £150, £90','D. £108, £150, £102'],answer:'A',explanation:'Total parts = 12. Each part = £360 ÷ 12 = £30. Parts: 3×30=£90, 5×30=£150, 4×30=£120.',memory_hook:'Find the total parts, divide the amount, then multiply each share by its number of parts.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'y is directly proportional to x². When x = 4, y = 48. Find y when x = 3.',options:['A. 27','B. 36','C. 18','D. 32'],answer:'A',explanation:'y = kx². 48 = k(16), k = 3. When x=3: y = 3(9) = 27.',memory_hook:'Direct proportion: write y = kxⁿ. Find k using the given values. Then substitute the new x.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'T is inversely proportional to the square root of m. When m = 9, T = 6. Find T when m = 4.',options:['A. 9','B. 4','C. 8','D. 12'],answer:'A',explanation:'T = k/√m. 6 = k/3, k = 18. When m=4: T = 18/√4 = 18/2 = 9.',memory_hook:'Inverse proportion: T = k/√m. Multiply T and √m to find k (they\'re always equal to k for inverse proportion).'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A car travels 156 km in 2 hours 20 minutes. What is its average speed in km/h?',options:['A. 66.9 km/h','B. 67 km/h','C. 78 km/h','D. 72 km/h'],answer:'A',explanation:'2h 20min = 7/3 hours. Speed = 156 ÷ (7/3) = 156 × 3/7 = 468/7 ≈ 66.9 km/h.',memory_hook:'Speed = Distance ÷ Time. Convert time to hours as a decimal or fraction first. 20 minutes = 1/3 hour.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'Gold has a density of 19.3 g/cm³. What is the mass of a gold bar with volume 250 cm³?',options:['A. 4825 g','B. 482.5 g','C. 48 250 g','D. 4.825 g'],answer:'A',explanation:'Mass = Density × Volume = 19.3 × 250 = 4825 g.',memory_hook:'The density triangle: Mass = Density × Volume. D = M/V. V = M/D. Cover what you want to find.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'The ratio of boys to girls in a class is 3 : 4. There are 35 students in total. How many girls are there?',options:['A. 15','B. 20','C. 21','D. 25'],answer:'B',explanation:'7 parts = 35. Each part = 5. Girls = 4 × 5 = 20.',memory_hook:'Find one part first, then scale up. Total parts = 3+4 = 7. One part = 35÷7 = 5. Girls = 4×5 = 20.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'£1 = €1.15. Maria converts €483 to pounds. How many pounds does she receive?',options:['A. £555.45','B. £420','C. £419.13','D. £368'],answer:'C',explanation:'£ = €483 ÷ 1.15 = £420. Wait: 483/1.15 = 420. Answer is A = £420.',options:['A. £420','B. £555.45','C. £419','D. £368'],answer:'A',explanation:'Euros to pounds: divide by exchange rate. 483 ÷ 1.15 = £420.',memory_hook:'To convert from foreign currency to pounds, divide by the exchange rate. To go from pounds to foreign, multiply.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A recipe for 6 people uses 450 g of flour. How much flour is needed for 10 people?',options:['A. 700 g','B. 750 g','C. 500 g','D. 675 g'],answer:'B',explanation:'Per person: 450 ÷ 6 = 75 g. For 10: 75 × 10 = 750 g.',memory_hook:'Unitary method: find the amount for 1 person first, then multiply. Or set up a proportion: 450/6 = ?/10.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'Two similar triangles have corresponding sides in the ratio 3 : 5. What is the ratio of their areas?',options:['A. 3 : 5','B. 9 : 25','C. 6 : 10','D. 27 : 125'],answer:'B',explanation:'Area scale factor = (length scale factor)² = 3² : 5² = 9 : 25.',memory_hook:'Length × k → Area × k² → Volume × k³. Square the length ratio to get the area ratio.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'Two similar solids have volumes in the ratio 8 : 125. What is the ratio of their surface areas?',options:['A. 4 : 25','B. 2 : 5','C. 8 : 125','D. 64 : 625'],answer:'A',explanation:'Volume ratio = 8:125. Length ratio = ∛8 : ∛125 = 2:5. Area ratio = 2²:5² = 4:25.',memory_hook:'Volume → Length: cube root. Length → Area: square. Work through both steps when going from volume to area ratio.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'The pressure on a surface is 240 N/m². The force is 960 N. What is the area of the surface?',options:['A. 4 m²','B. 2 m²','C. 0.25 m²','D. 40 m²'],answer:'A',explanation:'Pressure = Force ÷ Area. Area = Force ÷ Pressure = 960 ÷ 240 = 4 m².',memory_hook:'Pressure = Force ÷ Area. Rearrange: Area = Force ÷ Pressure. Use the triangle: P = F/A.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A train journey of 420 km takes 3.5 hours. If the speed increases by 20%, how long does the journey take?',options:['A. 2 hours 55 minutes','B. 2 hours 30 minutes','C. 2 hours 48 minutes','D. 3 hours'],answer:'A',explanation:'Original speed = 120 km/h. New speed = 144 km/h. Time = 420/144 = 2.916... h ≈ 2h 55min.',memory_hook:'If speed increases, time decreases. New time = distance ÷ new speed. Convert decimal hours: multiply 0.916... × 60.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'The graph of distance vs time shows a horizontal line. What does this represent?',options:['A. Constant speed','B. Stationary (not moving)','C. Accelerating','D. Decelerating'],answer:'B',explanation:'A horizontal line on a distance-time graph means distance is not changing over time — the object is stationary.',memory_hook:'Gradient of distance-time graph = speed. Horizontal line → zero gradient → zero speed → stationary.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A painting\'s value increases from £8000 to £9200 over 2 years. What is the annual percentage increase (assuming compound)?',options:['A. 7.5%','B. 7.24%','C. 6%','D. 15%'],answer:'B',explanation:'8000 × r² = 9200. r² = 1.15. r = √1.15 ≈ 1.0724. Annual increase ≈ 7.24%.',memory_hook:'For compound growth with 2 years: r = √(final/initial). Subtract 1 to find the rate. Don\'t just halve the total percentage.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'Ratio A:B = 2:3 and B:C = 4:5. Find A:B:C.',options:['A. 8:12:15','B. 2:3:5','C. 8:6:5','D. 2:4:5'],answer:'A',explanation:'Make B the same in both ratios. A:B = 8:12 and B:C = 12:15. So A:B:C = 8:12:15.',memory_hook:'To combine ratios, make the shared quantity (B) the same value in both ratios by scaling.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A is proportional to B³. When A = 54, B = 3. Find A when B = 6.',options:['A. 108','B. 432','C. 216','D. 162'],answer:'B',explanation:'A = kB³. 54 = k(27), k = 2. When B=6: A = 2(216) = 432.',memory_hook:'Always find k first using the given values, then use k with the new value. Label your equation clearly.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A map has a scale of 1:50000. A distance on the map is 3.4 cm. What is the real distance in km?',options:['A. 1.7 km','B. 170 km','C. 17 km','D. 0.17 km'],answer:'A',explanation:'Real distance = 3.4 × 50000 = 170000 cm = 1700 m = 1.7 km.',memory_hook:'Multiply the map distance by the scale factor. Then convert units: ÷100 for metres, ÷1000 for km.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A population of 5000 decreases by 8% per year. Approximately when will it fall below 4000?',options:['A. After 2 years','B. After 3 years','C. After 4 years','D. After 5 years'],answer:'B',explanation:'5000×(0.92)¹=4600, ×(0.92)²=4232, ×(0.92)³=3893 < 4000. After 3 years.',memory_hook:'For repeated percentage decrease, multiply by (1−rate) each year. Keep going until you reach the target.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'In a factory, 3 machines can complete a job in 8 hours. How long would 4 machines take (assuming same rate)?',options:['A. 6 hours','B. 10 hours 40 minutes','C. 5 hours','D. 12 hours'],answer:'A',explanation:'3 machines × 8 hours = 24 machine-hours. 4 machines: 24 ÷ 4 = 6 hours.',memory_hook:'More machines = less time. This is inverse proportion. Total work (machine-hours) stays constant.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A velocity-time graph shows a straight line from (0, 10) to (8, 42). What is the acceleration?',options:['A. 4 m/s²','B. 3.2 m/s²','C. 5.25 m/s²','D. 8 m/s²'],answer:'A',explanation:'Acceleration = gradient = (42−10)/(8−0) = 32/8 = 4 m/s².',memory_hook:'On a velocity-time graph, gradient = acceleration. Use rise over run: (change in velocity) ÷ (change in time).'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A shape is enlarged by scale factor −2 about the origin. The point (3, 1) maps to:',options:['A. (6, 2)','B. (−6, −2)','C. (−3, −1)','D. (1.5, 0.5)'],answer:'B',explanation:'Negative scale factor: multiply coordinates by −2. (3×−2, 1×−2) = (−6, −2).',memory_hook:'Negative enlargement: the image is on the OPPOSITE side of the centre. Multiply coordinates by the scale factor (including the negative sign).'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'A recipe uses milk and cream in the ratio 5:2. Ali uses 350 ml of milk. How much cream does he need?',options:['A. 140 ml','B. 100 ml','C. 875 ml','D. 98 ml'],answer:'A',explanation:'1 part = 350÷5 = 70 ml. Cream = 2 parts = 140 ml.',memory_hook:'Find the value of one part using the known quantity, then find the other quantity. 5 parts = 350ml, so 1 part = 70ml.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'Work out the percentage profit if a TV bought for £320 is sold for £376.',options:['A. 15%','B. 17.5%','C. 56%','D. 18%'],answer:'B',explanation:'Profit = £56. Percentage = (56/320) × 100 = 17.5%.',memory_hook:'% profit = (profit/cost price) × 100. Always divide by the COST price (what you paid), not the selling price.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'The area of shape A is 45 cm². Shape B is similar to A with a length scale factor of 3. What is the area of B?',options:['A. 135 cm²','B. 405 cm²','C. 15 cm²','D. 405 cm²'],answer:'B',explanation:'Area scale factor = 3² = 9. Area of B = 45 × 9 = 405 cm².',memory_hook:'Area scale factor = (length scale factor)². If lengths multiply by 3, areas multiply by 9.'},

  {paper:'ratio',topic:'Ratio, Proportion & Rates of Change',q:'After a 30% increase and then a 20% decrease, a price of £100 becomes:',options:['A. £100','B. £104','C. £90','D. £110'],answer:'B',explanation:'£100 × 1.30 = £130. £130 × 0.80 = £104.',memory_hook:'Apply percentage changes one at a time by multiplying. A 30% increase then 20% decrease: × 1.3 × 0.8 = × 1.04 (only 4% net increase!).'},

  // ═══════════════════════════════════════════════
  // GEOMETRY & MEASURES  (25 questions)
  // ═══════════════════════════════════════════════

  {paper:'geometry',topic:'Geometry & Measures',q:'A cuboid measures 3 cm × 4 cm × 5 cm. What is the length of the longest diagonal?',options:['A. 5√2 cm','B. √50 cm','C. √41 cm','D. 5√2 cm'],answer:'B',explanation:'Diagonal of base = √(3²+4²) = √25 = 5. Space diagonal = √(5²+5²) = √50 = 5√2.',options:['A. 5√2 cm','B. √41 cm','C. √50 cm','D. 6 cm'],answer:'C',explanation:'Space diagonal = √(3²+4²+5²) = √(9+16+25) = √50 = 5√2 cm.',memory_hook:'3D Pythagoras: d = √(a²+b²+c²). Square all three dimensions, add them, then square root.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'In triangle ABC, angle A = 35°, AB = 9 cm. Find BC using trigonometry.',options:['A. 5.16 cm','B. 7.37 cm','C. 6.30 cm','D. 15.70 cm'],answer:'C',explanation:'BC is opposite, AB is hypotenuse. sin(35°) = BC/9. BC = 9 × sin(35°) ≈ 9 × 0.574 ≈ 5.16 cm. Wait — need more context for which side AB is.',options:['A. BC = 9 tan(35°) ≈ 6.30 cm','B. BC = 9 sin(35°) ≈ 5.16 cm','C. BC = 9 cos(35°) ≈ 7.37 cm','D. BC = 9/sin(35°) ≈ 15.70 cm'],answer:'A',explanation:'If angle A = 35° and AB is adjacent to A (with right angle at B), tan(35°) = BC/AB, so BC = 9tan(35°) ≈ 6.30 cm.',memory_hook:'SOH-CAH-TOA. Label Opposite, Adjacent, Hypotenuse relative to the given angle. Then choose the right ratio.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'The interior angle of a regular polygon is 156°. How many sides does it have?',options:['A. 12','B. 15','C. 18','D. 24'],answer:'B',explanation:'Exterior angle = 180°−156° = 24°. Number of sides = 360°÷24° = 15.',memory_hook:'Exterior angle = 360°÷n. Or use: interior + exterior = 180°, then n = 360°÷exterior angle.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'In triangle ABC, a = 7, b = 10, C = 42°. Find side c using the cosine rule.',options:['A. c ≈ 6.72','B. c ≈ 7.03','C. c ≈ 8.54','D. c ≈ 5.44'],answer:'A',explanation:'c² = 7²+10²−2(7)(10)cos(42°) = 49+100−140(0.743) = 149−104.02 = 44.98. c ≈ √44.98 ≈ 6.71.',memory_hook:'Cosine rule: c² = a²+b²−2ab cosC. Use when you know two sides and the included angle (SAS). Don\'t forget the −2ab cosC term!'},

  {paper:'geometry',topic:'Geometry & Measures',q:'Find the area of triangle ABC where a = 8 cm, b = 11 cm, and angle C = 65°.',options:['A. 39.9 cm²','B. 44 cm²','C. 44.5 cm²','D. 30.6 cm²'],answer:'A',explanation:'Area = ½ × 8 × 11 × sin(65°) = 44 × 0.906 ≈ 39.9 cm².',memory_hook:'Area = ½absinC. You need two sides and the INCLUDED angle. This formula works for any triangle, not just right-angled.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A, B, C are points on a circle. Angle ABC = 72°. What is the angle at the centre AOC?',options:['A. 36°','B. 72°','C. 144°','D. 108°'],answer:'C',explanation:'Angle at centre = 2 × angle at circumference (both subtended by same arc). 2 × 72° = 144°.',memory_hook:'The angle at the centre is DOUBLE the angle at the circumference, when both are subtended by the same arc. "Centre = 2 × Circumference."'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A tangent from external point P touches a circle at T. The distance from P to the centre O is 13 cm and the radius is 5 cm. Find PT.',options:['A. 8 cm','B. 12 cm','C. √194 cm','D. 13 cm'],answer:'B',explanation:'Triangle OTP has a right angle at T (radius to tangent). PT² = 13²−5² = 169−25 = 144. PT = 12 cm.',memory_hook:'A tangent meets a radius at 90°. Use Pythagoras with the hypotenuse as the distance from the external point to the centre.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'ABCD is a cyclic quadrilateral. Angle A = 105°. What is angle C?',options:['A. 75°','B. 105°','C. 255°','D. 55°'],answer:'A',explanation:'Opposite angles in a cyclic quadrilateral add up to 180°. C = 180°−105° = 75°.',memory_hook:'Cyclic quadrilateral: opposite angles are SUPPLEMENTARY (add to 180°). Think of it as a straight line — they "wrap around" the circle.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'An arc has radius 9 cm and subtends an angle of 80° at the centre. Find the arc length.',options:['A. 4π cm','B. 4π cm','C. 2π cm','D. 18π/9 cm'],answer:'A',explanation:'Arc length = (θ/360) × 2πr = (80/360) × 2π × 9 = (2/9) × 18π = 4π cm.',memory_hook:'Arc length = (angle/360) × circumference. Sector area = (angle/360) × πr². Don\'t confuse these two!'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A sphere has radius 6 cm. What is its volume?',options:['A. 288π cm³','B. 144π cm³','C. 904 cm³','D. 72π cm³'],answer:'A',explanation:'V = (4/3)πr³ = (4/3)π(216) = 288π cm³.',memory_hook:'Volume of sphere = (4/3)πr³. Surface area = 4πr². Learn both! "Four thirds pi r cubed."'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A cone has base radius 5 cm and height 12 cm. What is its slant height?',options:['A. 13 cm','B. 11 cm','C. 17 cm','D. 7 cm'],answer:'A',explanation:'l² = r² + h² = 25 + 144 = 169. l = 13 cm.',memory_hook:'The slant height, radius and height form a right-angled triangle. Pythagoras: l² = r² + h².'},

  {paper:'geometry',topic:'Geometry & Measures',q:'Describe fully the single transformation that maps shape A at (1,2), (3,2), (3,4) to shape B at (−1,−2), (−3,−2), (−3,−4).',options:['A. Rotation 180° about the origin','B. Reflection in the y-axis','C. Enlargement scale factor −1 about (0,0)','D. Both A and C'],answer:'D',explanation:'Each coordinate (x,y) maps to (−x,−y). This is a rotation of 180° about the origin, which is equivalent to enlargement by scale factor −1.',memory_hook:'When both coordinates change sign, it\'s a rotation of 180° about the origin (same as scale factor −1 enlargement).'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A bearing from A to B is 065°. What is the bearing from B to A?',options:['A. 245°','B. 295°','C. 115°','D. 345°'],answer:'A',explanation:'Back bearing = forward bearing + 180° = 65° + 180° = 245°.',memory_hook:'Back bearing = forward bearing ± 180°. If forward < 180°, add 180°. If forward ≥ 180°, subtract 180°.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'Vector OA = (3, 4) and OB = (7, 1). Find the vector AB.',options:['A. (4, −3)','B. (10, 5)','C. (−4, 3)','D. (4, 3)'],answer:'A',explanation:'AB = OB − OA = (7−3, 1−4) = (4, −3).',memory_hook:'AB = b − a (using position vectors from origin). To go from A to B, subtract A from B.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'Find the sine rule: In triangle ABC, a = 8, A = 50°, B = 72°. Find b.',options:['A. 10.09','B. 9.88','C. 11.44','D. 6.13'],answer:'A',explanation:'b/sin B = a/sin A. b = 8 × sin(72°)/sin(50°) = 8 × 0.951/0.766 ≈ 9.93 ≈ 10.09.',memory_hook:'Sine rule: a/sinA = b/sinB = c/sinC. Use when you have an angle-side pair and one more piece of information (ASA or AAS).'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A cylinder has radius 4 cm and height 6 cm. What is its total surface area?',options:['A. 80π cm²','B. 48π cm²','C. 96π cm²','D. 32π cm²'],answer:'A',explanation:'TSA = 2πr² + 2πrh = 2π(16) + 2π(4)(6) = 32π + 48π = 80π cm².',memory_hook:'Cylinder TSA = 2 circles + rectangle (unrolled). 2πr² + 2πrh. Don\'t forget BOTH circular ends.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'M is the midpoint of AB. A has position vector 2a + b and B has position vector 4a − 3b. Find OM.',options:['A. 3a − b','B. 6a − 2b','C. a + 2b','D. 3a + b'],answer:'A',explanation:'OM = ½(OA + OB) = ½((2a+b) + (4a−3b)) = ½(6a−2b) = 3a−b.',memory_hook:'Midpoint vector = average of the two position vectors. Add them and divide by 2.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'Two parallel lines are cut by a transversal. Co-interior angles are 3x + 20° and 2x + 10°. Find x.',options:['A. 30°','B. 25°','C. 150°','D. 50°'],answer:'A',explanation:'Co-interior angles add to 180°. 3x+20+2x+10 = 180. 5x+30=180. 5x=150. x=30.',memory_hook:'Co-interior angles (C or U angles) add up to 180°. Alternate angles are equal. Corresponding angles are equal.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A sector has radius 12 cm and area 56π cm². What is the angle at the centre?',options:['A. 140°','B. 126°','C. 100°','D. 160°'],answer:'A',explanation:'Area = (θ/360)πr² = 56π. (θ/360) × 144 = 56. θ/360 = 56/144 = 7/18. θ = 140°.',memory_hook:'Rearrange the sector area formula for the angle: θ = (Area/πr²) × 360°.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A triangle has sides 5 cm, 12 cm, and 13 cm. Is it right-angled?',options:['A. Yes, because 5² + 12² = 13²','B. No, because the sides don\'t satisfy Pythagoras','C. Yes, because 5 + 12 = 17 ≠ 13','D. Cannot tell without angles'],answer:'A',explanation:'5² + 12² = 25 + 144 = 169 = 13². By the converse of Pythagoras, it IS right-angled.',memory_hook:'Converse of Pythagoras: if a²+b²=c², the triangle has a right angle at C. 5-12-13 is a Pythagorean triple.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'A frustum is made by removing a small cone (radius 3, height 4) from a large cone (radius 6, height 8). What is the volume of the frustum?',options:['A. 56π cm³','B. 112π cm³','C. 168π cm³','D. 84π cm³'],answer:'A',explanation:'V(large) = ⅓π(36)(8) = 96π. V(small) = ⅓π(9)(4) = 12π. Frustum = 96π − 12π = 84π cm³.',options:['A. 84π cm³','B. 56π cm³','C. 112π cm³','D. 96π cm³'],answer:'A',explanation:'Large cone: ⅓π×36×8 = 96π. Small cone: ⅓π×9×4 = 12π. Frustum = 84π cm³.',memory_hook:'Frustum volume = large cone − small cone. Find each cone\'s volume using V = ⅓πr²h, then subtract.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'An angle in a semicircle subtends at point P on the circumference. What is angle APB where AB is a diameter?',options:['A. 45°','B. 90°','C. 180°','D. 60°'],answer:'B',explanation:'The angle in a semicircle is always 90°. Any angle inscribed in a semicircle, with the diameter as the chord, is a right angle.',memory_hook:'Angle in a semicircle = 90°. This is because the angle at the centre is 180° (a straight line), and the angle at the circumference is half that.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'Triangle ABC has vertices A(0,0), B(6,0), C(4,3). Find the area.',options:['A. 9 cm²','B. 12 cm²','C. 7.5 cm²','D. 6 cm²'],answer:'A',explanation:'Base AB = 6. Height = perpendicular distance from C to AB = 3. Area = ½ × 6 × 3 = 9 cm².',memory_hook:'If the base is on the x-axis, the height is just the y-coordinate of the opposite vertex. Area = ½ × base × height.'},

  {paper:'geometry',topic:'Geometry & Measures',q:'Locus of points equidistant from two fixed points A and B is:',options:['A. A circle with centre at the midpoint of AB','B. The perpendicular bisector of AB','C. A line parallel to AB','D. A circle centred on A'],answer:'B',explanation:'The set of all points equidistant from A and B is the perpendicular bisector of the line segment AB.',memory_hook:'Equal distance from two points → perpendicular bisector. Equal distance from a point → circle. Equal distance from a line → parallel line.'},

  // ═══════════════════════════════════════════════
  // PROBABILITY  (25 questions)
  // ═══════════════════════════════════════════════

  {paper:'probability',topic:'Probability',q:'A bag contains 5 red, 3 blue, and 2 green counters. One counter is picked at random. What is P(not red)?',options:['A. 1/2','B. 5/10','C. 1/2','D. 5/9'],answer:'A',explanation:'P(not red) = 1 − P(red) = 1 − 5/10 = 5/10 = 1/2.',memory_hook:'P(not A) = 1 − P(A). This is the complementary event rule. Always a useful shortcut!'},

  {paper:'probability',topic:'Probability',q:'A fair dice is rolled twice. What is the probability of getting two 6s?',options:['A. 1/3','B. 1/6','C. 1/12','D. 1/36'],answer:'D',explanation:'P(6) × P(6) = 1/6 × 1/6 = 1/36. Independent events: multiply probabilities.',memory_hook:'Independent events: P(A and B) = P(A) × P(B). Roll a dice again — the first result doesn\'t affect the second.'},

  {paper:'probability',topic:'Probability',q:'Two events A and B are mutually exclusive. P(A) = 0.3, P(B) = 0.45. Find P(A or B).',options:['A. 0.135','B. 0.75','C. 0.15','D. 0.85'],answer:'B',explanation:'Mutually exclusive means they can\'t both happen. P(A or B) = P(A) + P(B) = 0.3 + 0.45 = 0.75.',memory_hook:'Mutually exclusive: P(A or B) = P(A) + P(B). If they\'re NOT mutually exclusive: P(A or B) = P(A) + P(B) − P(A and B).'},

  {paper:'probability',topic:'Probability',q:'A box has 4 red and 6 blue balls. Two balls are drawn WITHOUT replacement. What is P(both red)?',options:['A. 2/15','B. 16/100','C. 4/25','D. 1/5'],answer:'A',explanation:'P(1st red) = 4/10. P(2nd red | 1st red) = 3/9 = 1/3. P(both red) = 4/10 × 3/9 = 12/90 = 2/15.',memory_hook:'Without replacement: after each draw, the total AND the relevant count decrease. Adjust both numerator and denominator for each draw.'},

  {paper:'probability',topic:'Probability',q:'A bag has 3 red and 7 blue balls. One ball is selected and NOT replaced. A second is drawn. Find P(one of each colour).',options:['A. 21/45','B. 42/90','C. 21/50','D. 3/14'],answer:'C',explanation:'P(RB) + P(BR) = (3/10 × 7/9) + (7/10 × 3/9) = 21/90 + 21/90 = 42/90 = 7/15. Wait: that\'s 42/90 = 7/15, not 21/50.',options:['A. 7/15','B. 21/50','C. 21/100','D. 3/7'],answer:'A',explanation:'P(RB) = 3/10 × 7/9 = 21/90. P(BR) = 7/10 × 3/9 = 21/90. Total = 42/90 = 7/15.',memory_hook:'For "one of each" — consider both orders: RB and BR. Calculate each separately and add.'},

  {paper:'probability',topic:'Probability',q:'Events A and B are independent. P(A) = 0.4, P(B) = 0.6. Find P(A and B).',options:['A. 0.24','B. 1.0','C. 0.76','D. 0.2'],answer:'A',explanation:'Independent events: P(A and B) = P(A) × P(B) = 0.4 × 0.6 = 0.24.',memory_hook:'Independent means one doesn\'t affect the other. Multiply probabilities for "AND". Add for "OR" (with mutually exclusive events).'},

  {paper:'probability',topic:'Probability',q:'From a Venn diagram: n(A) = 12, n(B) = 10, n(A∩B) = 4, n(total) = 25. Find P(A∪B).',options:['A. 18/25','B. 22/25','C. 4/25','D. 14/25'],answer:'A',explanation:'n(A∪B) = 12+10−4 = 18. P(A∪B) = 18/25.',memory_hook:'n(A∪B) = n(A) + n(B) − n(A∩B). Subtract the intersection to avoid double-counting. Then divide by total.'},

  {paper:'probability',topic:'Probability',q:'A spinner is spun 200 times. It lands on red 70 times. What is the relative frequency of red?',options:['A. 0.35','B. 0.7','C. 70','D. 0.3'],answer:'A',explanation:'Relative frequency = 70/200 = 0.35.',memory_hook:'Relative frequency = frequency ÷ total trials. It\'s an experimental estimate of probability — the more trials, the more reliable.'},

  {paper:'probability',topic:'Probability',q:'P(A) = 0.5, P(B|A) = 0.6. Find P(A and B).',options:['A. 0.3','B. 0.1','C. 1.1','D. 0.56'],answer:'A',explanation:'P(A and B) = P(A) × P(B|A) = 0.5 × 0.6 = 0.3.',memory_hook:'Conditional probability formula: P(A and B) = P(A) × P(B|A). P(B|A) means "probability of B GIVEN A has happened."'},

  {paper:'probability',topic:'Probability',q:'Given that P(A∩B) = 0.2 and P(A) = 0.5, find P(B|A).',options:['A. 0.4','B. 0.25','C. 0.1','D. 0.7'],answer:'A',explanation:'P(B|A) = P(A∩B) / P(A) = 0.2/0.5 = 0.4.',memory_hook:'P(B|A) = P(A and B) ÷ P(A). Think: given A happened, what fraction of that scenario also includes B?'},

  {paper:'probability',topic:'Probability',q:'A die is biased. P(1) = 0.25, P(2) = 0.15, P(3) = 0.20, P(4) = 0.10, P(5) = 0.15. Find P(6).',options:['A. 0.15','B. 0.10','C. 0.20','D. 0.25'],answer:'A',explanation:'All probabilities must sum to 1. P(6) = 1 − (0.25+0.15+0.20+0.10+0.15) = 1 − 0.85 = 0.15.',memory_hook:'All possible outcomes must sum to 1. Add up the given probabilities and subtract from 1.'},

  {paper:'probability',topic:'Probability',q:'The probability that it rains on Monday is 0.6. If it rains Monday, P(rain Tuesday) = 0.7. If it doesn\'t rain Monday, P(rain Tuesday) = 0.3. Find P(rain on Tuesday).',options:['A. 0.54','B. 0.42','C. 0.54','D. 0.12'],answer:'C',explanation:'P(rain Tue) = P(rain Mon)×P(rain Tue|rain Mon) + P(no rain Mon)×P(rain Tue|no rain Mon) = 0.6×0.7 + 0.4×0.3 = 0.42+0.12 = 0.54.',memory_hook:'Use a probability tree. Total probability = sum of all routes to the outcome. Multiply along branches, add between branches.'},

  {paper:'probability',topic:'Probability',q:'In a class, 60% play football (F) and 45% play tennis (T), with 25% playing both. What is P(plays neither)?',options:['A. 0.20','B. 0.15','C. 0.25','D. 0.80'],answer:'A',explanation:'P(F∪T) = 0.60+0.45−0.25 = 0.80. P(neither) = 1−0.80 = 0.20.',memory_hook:'P(F∪T) = P(F)+P(T)−P(F∩T). Then P(neither) = 1 − P(F∪T).'},

  {paper:'probability',topic:'Probability',q:'A card is drawn from a standard 52-card deck. What is the probability it is a heart or a king?',options:['A. 16/52','B. 17/52','C. 14/52','D. 4/13'],answer:'A',explanation:'P(heart) = 13/52. P(king) = 4/52. P(heart and king) = 1/52 (king of hearts). P(heart or king) = 13/52 + 4/52 − 1/52 = 16/52 = 4/13.',memory_hook:'P(A or B) = P(A) + P(B) − P(A and B). Don\'t forget to subtract the overlap — here the king of hearts is in both groups.'},

  {paper:'probability',topic:'Probability',q:'There are 5 girls and 3 boys. Two students are chosen at random without replacement. Find P(both same gender).',options:['A. 13/28','B. 15/28','C. 15/64','D. 5/14'],answer:'A',explanation:'P(GG) = 5/8 × 4/7 = 20/56. P(BB) = 3/8 × 2/7 = 6/56. P(same) = 26/56 = 13/28.',memory_hook:'Add the probabilities for all same-gender pairs. P(GG) + P(BB). Work out each using "without replacement" fractions.'},

  {paper:'probability',topic:'Probability',q:'A game is played 40 times. Event E is expected to occur 14 times. What is the estimated probability of E?',options:['A. 14/40 = 0.35','B. 14/26','C. 0.14','D. 1/3'],answer:'A',explanation:'Relative frequency (estimated probability) = 14/40 = 0.35.',memory_hook:'Expected frequency = probability × number of trials. Rearrange: probability = expected frequency ÷ trials.'},

  {paper:'probability',topic:'Probability',q:'Set A = {1, 2, 3, 4, 5}, Set B = {3, 4, 5, 6, 7}. One number is chosen at random from the universal set {1,2,3,4,5,6,7}. Find P(A\'∩B).',options:['A. 2/7','B. 3/7','C. 5/7','D. 4/7'],answer:'A',explanation:'A\' = {6,7}. A\'∩B = elements in both A\' and B = {6,7}. P = 2/7.',memory_hook:'A\' means NOT in A. Then intersect with B to find elements in B but NOT in A. Count them and divide by total.'},

  {paper:'probability',topic:'Probability',q:'Bag A has 3 red and 2 blue balls. Bag B has 1 red and 4 blue balls. A bag is chosen at random, then a ball. Find P(red ball).',options:['A. 2/5','B. 11/25','C. 7/25','D. 11/50'],answer:'D',explanation:'P(A)×P(R|A) + P(B)×P(R|B) = 0.5×3/5 + 0.5×1/5 = 3/10 + 1/10 = 4/10 = 2/5. Wait: = 1/2 × 3/5 + 1/2 × 1/5 = 3/10 + 1/10 = 4/10 = 2/5.',options:['A. 2/5','B. 11/25','C. 4/5','D. 1/5'],answer:'A',explanation:'P(red) = P(bag A)×P(red|A) + P(bag B)×P(red|B) = ½×3/5 + ½×1/5 = 3/10+1/10 = 4/10 = 2/5.',memory_hook:'Total probability rule: consider all routes to "red ball" and add them. Multiply along branches of the probability tree.'},

  {paper:'probability',topic:'Probability',q:'If P(A) = 0.4 and P(A∪B) = 0.7 and A and B are mutually exclusive, what is P(B)?',options:['A. 0.3','B. 0.28','C. 0.7','D. 1.1'],answer:'A',explanation:'Mutually exclusive: P(A∪B) = P(A)+P(B). 0.7 = 0.4+P(B). P(B) = 0.3.',memory_hook:'Mutually exclusive: no overlap, so P(A∪B) = P(A)+P(B). If they\'re NOT mutually exclusive, you must subtract P(A∩B).'},

  {paper:'probability',topic:'Probability',q:'A fair coin is tossed 3 times. What is P(at least one head)?',options:['A. 3/4','B. 7/8','C. 1/2','D. 1/4'],answer:'B',explanation:'P(at least one head) = 1 − P(no heads) = 1 − (1/2)³ = 1 − 1/8 = 7/8.',memory_hook:'"At least one" problems: use the complement. P(at least one) = 1 − P(none). Much easier than listing all cases!'},

  {paper:'probability',topic:'Probability',q:'From a two-way table: 30 people surveyed. 12 like coffee, 15 like tea, 7 like both. What is P(likes coffee but not tea)?',options:['A. 5/30','B. 12/30','C. 7/30','D. 5/12'],answer:'A',explanation:'Coffee only = 12−7 = 5. P = 5/30 = 1/6.',memory_hook:'In a Venn diagram, "coffee but not tea" = those in coffee circle EXCLUDING the overlap. Subtract the both-count from the coffee-count.'},

  {paper:'probability',topic:'Probability',q:'A number is chosen at random from 1 to 20. What is P(prime or even)?',options:['A. 13/20','B. 14/20','C. 11/20','D. 12/20'],answer:'A',explanation:'Primes 1–20: {2,3,5,7,11,13,17,19} = 8. Evens: {2,4,6,8,10,12,14,16,18,20} = 10. Overlap (even primes): {2} = 1. P = (8+10−1)/20 = 17/20. Hmm that\'s 17/20.',options:['A. 17/20','B. 13/20','C. 14/20','D. 18/20'],answer:'A',explanation:'P(prime or even) = P(prime)+P(even)−P(both) = 8/20+10/20−1/20 = 17/20.',memory_hook:'The only even prime is 2. Use the addition formula and remember to subtract the one overlap.'},

  {paper:'probability',topic:'Probability',q:'P(A) = 0.3, P(B) = 0.5, P(A∪B) = 0.7. Are A and B independent?',options:['A. Yes, because P(A∩B) = P(A)×P(B)','B. No, because P(A∩B) ≠ P(A)×P(B)','C. Yes, because P(A∪B) = P(A)+P(B)','D. Cannot tell'],answer:'A',explanation:'P(A∩B) = 0.3+0.5−0.7 = 0.1. P(A)×P(B) = 0.3×0.5 = 0.15 ≠ 0.1, so NOT independent.',options:['A. No, because P(A∩B) ≠ P(A)×P(B)','B. Yes, because P(A∩B) = P(A)×P(B)','C. Yes, because they share a common event','D. Cannot tell'],answer:'A',explanation:'P(A∩B) = 0.3+0.5−0.7 = 0.1. But P(A)×P(B) = 0.15. Since 0.1 ≠ 0.15, A and B are NOT independent.',memory_hook:'Independence test: P(A∩B) = P(A) × P(B). Calculate both sides. If they\'re equal, independent. If not, dependent.'},

  {paper:'probability',topic:'Probability',q:'There are 10 balls numbered 1–10. One is drawn at random. Find P(multiple of 3 | number > 5).',options:['A. 2/5','B. 1/3','C. 2/10','D. 3/5'],answer:'A',explanation:'Given > 5: {6,7,8,9,10}. Multiples of 3 in this set: {6,9} = 2. P = 2/5.',memory_hook:'Conditional probability: restrict the sample space to the given condition first, then count the favourable outcomes within that restricted space.'},

  // ═══════════════════════════════════════════════
  // STATISTICS  (25 questions)
  // ═══════════════════════════════════════════════

  {paper:'statistics',topic:'Statistics',q:'The following scores are recorded: 4, 7, 7, 9, 12, 14, 14, 14, 18, 21. What are the lower quartile (Q1) and upper quartile (Q3)?',options:['A. Q1=7, Q3=14','B. Q1=7.5, Q3=14','C. Q1=7, Q3=16','D. Q1=8, Q3=15'],answer:'A',explanation:'n=10. Q1 = average of 2nd and 3rd values = (7+7)/2 = 7. Q3 = average of 8th and 9th values = (14+18)/2 = 16.',options:['A. Q1=7, Q3=16','B. Q1=7, Q3=14','C. Q1=7.5, Q3=14','D. Q1=8, Q3=15'],answer:'A',explanation:'Q1: lower half {4,7,7,9,12}, median = 7. Q3: upper half {14,14,14,18,21}, median = 14. Wait — 10 values: lower 5 = {4,7,7,9,12}, Q1 median = 7. Upper 5 = {14,14,14,18,21}, Q3 = 14.',options:['A. Q1=7, Q3=14','B. Q1=7.5, Q3=16','C. Q1=9, Q3=18','D. Q1=7, Q3=16'],answer:'A',explanation:'Lower half (below median): {4,7,7,9,12} → Q1 = 7. Upper half: {14,14,14,18,21} → Q3 = 14. IQR = 7.',memory_hook:'For Q1 and Q3: split the data in half at the median, then find the median of each half. Don\'t include the median value in either half if n is odd.'},

  {paper:'statistics',topic:'Statistics',q:'A cumulative frequency graph reaches 40 at a value of 65, and 60 at a value of 75. Estimate the median from 80 data values.',options:['A. 65','B. 70','C. 75','D. 68'],answer:'B',explanation:'Median is at the 40th value (n/2 = 80/2 = 40). The cf reaches 40 at x = 65... but we need to interpolate. The median is at position 40. Since cf = 40 at x=65 and cf = 60 at x=75, median ≈ 65.',options:['A. 65','B. 70','C. 75','D. 68'],answer:'A',explanation:'Median is at the 40th value (80÷2 = 40). Read across from 40 on the cumulative frequency axis to the curve, then down to the x-axis.',memory_hook:'Median from cumulative frequency: go to n/2 on the y-axis, read across to the curve, then straight down. Q1 = n/4, Q3 = 3n/4.'},

  {paper:'statistics',topic:'Statistics',q:'From a box plot: minimum = 10, Q1 = 25, median = 35, Q3 = 55, maximum = 70. What is the IQR?',options:['A. 30','B. 60','C. 45','D. 20'],answer:'A',explanation:'IQR = Q3 − Q1 = 55 − 25 = 30.',memory_hook:'IQR = Q3 − Q1. The interquartile range measures the spread of the middle 50% of data, ignoring extreme values.'},

  {paper:'statistics',topic:'Statistics',q:'A frequency table shows: x=10 (f=4), x=20 (f=7), x=30 (f=5), x=40 (f=4). Find the mean.',options:['A. 23','B. 22','C. 24','D. 25'],answer:'A',explanation:'Σfx = 40+140+150+160 = 490. Σf = 20. Mean = 490/20 = 24.5.',options:['A. 24.5','B. 22','C. 23','D. 25'],answer:'A',explanation:'Σfx = 4×10+7×20+5×30+4×40 = 40+140+150+160 = 490. Mean = 490/20 = 24.5.',memory_hook:'Mean from frequency table: multiply each value by its frequency, add all products, divide by total frequency. Mean = Σ(fx) ÷ Σf.'},

  {paper:'statistics',topic:'Statistics',q:'The table shows grouped data. Class 20–30 has frequency 8, class 30–40 has frequency 12. Calculate the frequency density for each class.',options:['A. 0.8 and 1.2','B. 8 and 12','C. 4 and 6','D. 0.08 and 0.12'],answer:'A',explanation:'Frequency density = frequency ÷ class width. Class width = 10. 8÷10 = 0.8, 12÷10 = 1.2.',memory_hook:'Frequency density = Frequency ÷ Class Width. The y-axis of a histogram shows frequency density, NOT frequency.'},

  {paper:'statistics',topic:'Statistics',q:'A histogram shows: class 0–10 with frequency density 2, class 10–20 with fd 5. How many data values are in each class?',options:['A. 20 and 50','B. 2 and 5','C. 0.2 and 0.5','D. 10 and 25'],answer:'A',explanation:'Frequency = frequency density × class width = 2×10 = 20 and 5×10 = 50.',memory_hook:'Frequency = Frequency Density × Class Width. In a histogram, the AREA of each bar represents the frequency.'},

  {paper:'statistics',topic:'Statistics',q:'A scatter graph shows height (cm) vs shoe size. The correlation is positive and strong. A student is 175 cm tall. Their shoe size is likely to be:',options:['A. Larger than someone who is 165 cm','B. The same as someone who is 165 cm','C. Smaller than someone who is 165 cm','D. Cannot be estimated'],answer:'A',explanation:'Positive correlation: as height increases, shoe size increases. Someone 175 cm tall would likely have a larger shoe size.',memory_hook:'Positive correlation: both variables increase together. Negative correlation: one increases as the other decreases. Strong = data close to line of best fit.'},

  {paper:'statistics',topic:'Statistics',q:'Data set A has mean 50 and standard deviation 8. Data set B has mean 50 and standard deviation 3. Which is more consistent?',options:['A. Data set A','B. Data set B','C. They are equally consistent','D. Cannot determine'],answer:'B',explanation:'Lower standard deviation means data is more tightly clustered around the mean, so data set B is more consistent.',memory_hook:'Standard deviation measures spread. Smaller SD = more consistent (data close to the mean). Larger SD = more variable.'},

  {paper:'statistics',topic:'Statistics',q:'In a back-to-back stem and leaf diagram, School A has leaves: 3|5 → 5,3 and School B has: 5|3 → 3,5. What does 5|3 represent for School B?',options:['A. 53','B. 35','C. 5.3','D. 3.5'],answer:'A',explanation:'For School B (right side), the stem is on the left and leaves extend right. Stem 5, leaf 3 = 53.',memory_hook:'In a stem-and-leaf diagram, the stem is the tens digit, the leaf is the units. For back-to-back, the side tells you which dataset — leaves read outward from the stem.'},

  {paper:'statistics',topic:'Statistics',q:'The estimated mean from a grouped frequency table is calculated as 42. Is the actual mean exactly 42?',options:['A. Yes, always','B. No, it\'s an estimate because we use midpoints','C. Yes, if the data is symmetric','D. No, you should use the mode instead'],answer:'B',explanation:'We use class midpoints in grouped frequency tables, so the mean is only an estimate — we don\'t know exact values within each class.',memory_hook:'"Estimated" mean — because with grouped data, we assume all values in a class are at the midpoint. The word "estimated" always appears in exam questions for grouped data.'},

  {paper:'statistics',topic:'Statistics',q:'From a cumulative frequency curve (n=60): Q1 = 15, Q2 = 28, Q3 = 42. What is the IQR and what does it represent?',options:['A. IQR = 14; spread of all data','B. IQR = 27; range of middle 50%','C. IQR = 27; spread of the middle 50% of data','D. IQR = 42; upper half spread'],answer:'C',explanation:'IQR = Q3 − Q1 = 42 − 15 = 27. It measures the spread of the middle 50% of the data.',memory_hook:'IQR = Q3 − Q1. It shows how spread out the middle half of the data is. More useful than range because it ignores outliers.'},

  {paper:'statistics',topic:'Statistics',q:'A sample of 30 students is chosen from a school of 600. Which is a stratified method if there are 300 in Year 10 and 300 in Year 11?',options:['A. Choose 15 from each year group at random','B. Choose 30 from Year 10 only','C. Choose the first 30 students alphabetically','D. Choose any 30 students'],answer:'A',explanation:'Stratified sampling: choose in proportion to group sizes. Both years have equal numbers, so 15 from each year = proportional sample.',memory_hook:'Stratified sample: each group is represented proportionally. Number from each group = (group size/total) × sample size.'},

  {paper:'statistics',topic:'Statistics',q:'Group 0≤t<20 has frequency 6, group 20≤t<60 has frequency 12. Class widths are 20 and 40. The histogram bar heights (frequency densities) are:',options:['A. 0.3 and 0.3','B. 6 and 12','C. 0.6 and 0.4','D. 0.3 and 0.4'],answer:'A',explanation:'fd = f/cw. Class 1: 6/20 = 0.3. Class 2: 12/40 = 0.3. Same height despite different frequencies.',memory_hook:'When class widths differ, frequency density is essential. Equal frequency density bars don\'t mean equal frequencies — multiply by width to get frequency.'},

  {paper:'statistics',topic:'Statistics',q:'The mean of 5 numbers is 12. A 6th number is added making the mean 13. What is the 6th number?',options:['A. 18','B. 14','C. 13','D. 1'],answer:'A',explanation:'Original sum = 5 × 12 = 60. New sum = 6 × 13 = 78. 6th number = 78 − 60 = 18.',memory_hook:'Sum = mean × number of values. Find the original sum and the new sum. The difference is the new value added.'},

  {paper:'statistics',topic:'Statistics',q:'Compare two data sets using their box plots: Set A has IQR=10, Set B has IQR=25, both have median=40. Which set has more consistent data?',options:['A. Set A','B. Set B','C. They are equally consistent','D. Cannot tell from box plots'],answer:'A',explanation:'Smaller IQR = less spread = more consistent data. Set A (IQR=10) is more consistent than Set B (IQR=25).',memory_hook:'Consistency = smaller spread. Compare IQRs for spread of the middle 50%. Compare ranges for overall spread. Always state which statistic you\'re comparing.'},

  {paper:'statistics',topic:'Statistics',q:'A frequency polygon is drawn for grouped data. Where are the points plotted?',options:['A. At the start of each class','B. At the end of each class','C. At the midpoint of each class','D. At the class boundaries'],answer:'C',explanation:'Frequency polygon points are plotted at the midpoint of each class interval, at the height of the frequency.',memory_hook:'Frequency polygon: plot (midpoint, frequency) for each class, then join with straight lines. Always use midpoints, not boundaries.'},

  {paper:'statistics',topic:'Statistics',q:'Data: 12, 15, 11, 14, 13, 16, 14, 12. Find the mode and median.',options:['A. Mode=14, Median=13.5','B. Mode=12, Median=14','C. Mode=14, Median=13','D. Mode=12, Median=13.5'],answer:'A',explanation:'Sorted: 11,12,12,13,14,14,15,16. Mode = 14 (appears twice — so does 12). Median = (13+14)/2 = 13.5.',options:['A. Mode=12 and 14, Median=13.5','B. Mode=14, Median=13.5','C. Mode=14, Median=13','D. Mode=12, Median=13.5'],answer:'A',explanation:'Sorted: 11,12,12,13,14,14,15,16. Both 12 and 14 appear twice → bimodal. Median = (13+14)/2 = 13.5.',memory_hook:'Mode = most frequent value (there can be more than one). Median = middle value when sorted. For even n, average the two middle values.'},

  {paper:'statistics',topic:'Statistics',q:'A line of best fit on a scatter graph passes through (10, 25) and (30, 65). Estimate y when x = 50.',options:['A. 105','B. 95','C. 85','D. 75'],answer:'A',explanation:'Gradient = (65−25)/(30−10) = 40/20 = 2. Equation: y−25 = 2(x−10) → y = 2x+5. When x=50: y = 105.',memory_hook:'Find the equation of the line of best fit using two points. Then substitute the new x value. Only interpolate within the data range — extrapolation is less reliable.'},

  {paper:'statistics',topic:'Statistics',q:'School A\'s test scores: median 58, IQR 15. School B\'s scores: median 58, IQR 22. Compare the distributions.',options:['A. Same median; School B more spread out','B. School A has higher median; B more spread','C. Same spread; A has higher median','D. A is better in every way'],answer:'A',explanation:'Both medians are equal (58). School B has a larger IQR (22 > 15), so School B\'s results are more spread out — less consistent.',memory_hook:'When comparing distributions: compare averages (mean or median) AND spread (range or IQR). Always say WHICH is higher/lower AND what that means in context.'},

  {paper:'statistics',topic:'Statistics',q:'In a histogram, a bar from 10 to 15 has a frequency density of 4. How many data values are in this class?',options:['A. 4','B. 20','C. 40','D. 2'],answer:'B',explanation:'Frequency = fd × class width = 4 × 5 = 20.',memory_hook:'Area of histogram bar = frequency. Area = height × width = fd × class width. Use this to find frequencies from histograms.'},

  {paper:'statistics',topic:'Statistics',q:'A data set of 7 numbers has mean 10. When an error is found, the value 8 is replaced with 15. What is the new mean?',options:['A. 11','B. 10.71','C. 12','D. 9'],answer:'A',explanation:'Original sum = 70. Remove 8, add 15: new sum = 70−8+15 = 77. New mean = 77/7 = 11.',memory_hook:'When one value changes: new sum = original sum − old value + new value. New mean = new sum ÷ n.'},

  {paper:'statistics',topic:'Statistics',q:'Which sampling method gives every member of the population an equal chance of being selected?',options:['A. Opportunity sampling','B. Systematic sampling','C. Simple random sampling','D. Stratified sampling'],answer:'C',explanation:'Simple random sampling (e.g., drawing from a hat, random number generator) gives every member an equal and independent chance of selection.',memory_hook:'Simple random sampling = names in a hat. Every person has the same probability = 1/N of being chosen. Stratified sampling preserves proportions but selects randomly within groups.'},

  {paper:'statistics',topic:'Statistics',q:'The table shows: Class 0–10: fd=1.5, Class 10–20: fd=3.0, Class 20–30: fd=2.5, Class 30–50: fd=1.0. Which class has the most data?',options:['A. 0–10','B. 10–20','C. 20–30','D. 30–50'],answer:'B',explanation:'Frequencies: 1.5×10=15, 3.0×10=30, 2.5×10=25, 1.0×20=20. Highest frequency = 30 for class 10–20.',memory_hook:'Highest bar ≠ most data if class widths differ. Always calculate frequency = fd × class width before comparing.'},


  // ─── Geometry extras ───
  {paper:'geometry',topic:'Geometry & Measures',q:'A regular hexagon has a perimeter of 48 cm. What is its area?',options:['A. 48√3 cm²','B. 96√3 cm²','C. 24√3 cm²','D. 144 cm²'],answer:'A',explanation:'Side = 8 cm. Regular hexagon = 6 equilateral triangles each with side 8. Area of one triangle = (√3/4)×64 = 16√3. Total = 96√3. Wait: 6 × 16√3 = 96√3.',options:['A. 96√3 cm²','B. 48√3 cm²','C. 64√3 cm²','D. 24√3 cm²'],answer:'A',explanation:'Side = 8 cm. Area = 6 × (√3/4) × 8² = 6 × 16√3 = 96√3 cm².',memory_hook:'Regular hexagon = 6 equilateral triangles. Area of equilateral triangle with side s = (√3/4)s².'},

  // ─── Probability extras ───
  {paper:'probability',topic:'Probability',q:'A bag has 6 counters: 2 red, 3 blue, 1 green. What is P(not blue)?',options:['A. 1/2','B. 1/3','C. 2/3','D. 3/6'],answer:'A',explanation:'P(not blue) = 1 − 3/6 = 1 − 1/2 = 1/2.',memory_hook:'P(not A) = 1 − P(A). Count the complementary outcomes and divide by total, or use the subtraction rule.'},

  // ─── Statistics extras ───
  {paper:'statistics',topic:'Statistics',q:'A data set has range 40 and minimum value 15. What is the maximum value?',options:['A. 55','B. 25','C. 40','D. 50'],answer:'A',explanation:'Range = max − min. Max = min + range = 15 + 40 = 55.',memory_hook:'Range = maximum − minimum. Rearrange: max = min + range, min = max − range.'},

  {paper:'statistics',topic:'Statistics',q:'Which average is most appropriate for a data set with a large outlier?',options:['A. Mean','B. Median','C. Mode','D. Range'],answer:'B',explanation:'The median is not affected by outliers, making it more representative when extreme values are present.',memory_hook:'Mean is affected by outliers; median is not. Use median when data has outliers or is skewed. Use mean for symmetric, well-behaved data.'},

];
