const MATHS_Q = [
  // ─── Number ───
  {paper:'number',topic:'Number',q:'What is 15% of 340?',options:['A. 34','B. 45','C. 51','D. 56'],answer:'C',explanation:'10% of 340 = 34. 5% = 17. 10% + 5% = 51.',memory_hook:'Break percentages into 10% chunks. 10% of 340 = 34, half of that is 17. Add them: 51.'},
  {paper:'number',topic:'Number',q:'Write 0.00047 in standard form.',options:['A. 4.7 × 10⁻³','B. 4.7 × 10⁻⁴','C. 47 × 10⁻⁵','D. 4.7 × 10⁴'],answer:'B',explanation:'Move the decimal point 4 places right to get 4.7, so the power is −4.',memory_hook:'Count how many places you move the decimal to get a number between 1 and 10. Moving right = negative power.'},
  {paper:'number',topic:'Number',q:'What is the LCM of 12 and 18?',options:['A. 6','B. 24','C. 36','D. 72'],answer:'C',explanation:'Multiples of 12: 12, 24, 36. Multiples of 18: 18, 36. The lowest common multiple is 36.',memory_hook:'LCM = smallest number both divide into exactly. List multiples of each and find the first one they share.'},
  {paper:'number',topic:'Number',q:'A price increases from £80 to £92. What is the percentage increase?',options:['A. 12%','B. 13%','C. 14%','D. 15%'],answer:'D',explanation:'Increase = 12. (12 ÷ 80) × 100 = 15%.',memory_hook:'% change = (change ÷ original) × 100. Always divide by the ORIGINAL value, not the new one.'},
  {paper:'number',topic:'Number',q:'Simplify the ratio 45 : 30.',options:['A. 9 : 6','B. 3 : 2','C. 5 : 3','D. 15 : 10'],answer:'B',explanation:'Divide both by the HCF, which is 15. 45 ÷ 15 = 3, 30 ÷ 15 = 2. Simplified ratio is 3 : 2.',memory_hook:'To simplify a ratio, find the HCF and divide both sides by it. Keep dividing until you can\'t simplify any further.'},
  {paper:'number',topic:'Number',q:'What is 2³ × 2⁴?',options:['A. 2⁷','B. 4⁷','C. 2¹²','D. 4¹²'],answer:'A',explanation:'When multiplying indices with the same base, add the powers: 2³ × 2⁴ = 2^(3+4) = 2⁷.',memory_hook:'Same base, multiplying? ADD the powers. 2³ × 2⁴ = 2⁷. Think: you\'re collecting 3 twos then 4 more twos — that\'s 7 twos.'},
  {paper:'number',topic:'Number',q:'Express 360 as a product of its prime factors.',options:['A. 2² × 3² × 5','B. 2³ × 3² × 5','C. 2² × 3 × 5²','D. 2³ × 3 × 5²'],answer:'B',explanation:'360 = 8 × 45 = 8 × 9 × 5 = 2³ × 3² × 5.',memory_hook:'Use a factor tree. Keep splitting until you have only prime numbers left. Circle the primes, then write them as powers.'},

  // ─── Algebra ───
  {paper:'algebra',topic:'Algebra',q:'Solve 3x + 7 = 22.',options:['A. x = 3','B. x = 4','C. x = 5','D. x = 6'],answer:'C',explanation:'3x = 22 − 7 = 15. x = 15 ÷ 3 = 5.',memory_hook:'Do the same thing to both sides. First subtract 7 from both sides, then divide both sides by 3.'},
  {paper:'algebra',topic:'Algebra',q:'Expand and simplify (x + 3)(x − 2).',options:['A. x² + x − 6','B. x² − x − 6','C. x² + x + 6','D. x² + 5x − 6'],answer:'A',explanation:'x² − 2x + 3x − 6 = x² + x − 6.',memory_hook:'FOIL: First, Outside, Inside, Last. x×x=x², x×(−2)=−2x, 3×x=3x, 3×(−2)=−6. Collect like terms.'},
  {paper:'algebra',topic:'Algebra',q:'The nth term of a sequence is 4n − 1. What is the 6th term?',options:['A. 21','B. 23','C. 24','D. 25'],answer:'B',explanation:'Substitute n = 6: 4(6) − 1 = 24 − 1 = 23.',memory_hook:'nth term formulas are just substitution. Swap n for the term number and calculate. 4×6−1 = 23.'},
  {paper:'algebra',topic:'Algebra',q:'Factorise x² + 5x + 6.',options:['A. (x + 1)(x + 6)','B. (x + 2)(x + 3)','C. (x − 2)(x − 3)','D. (x + 6)(x − 1)'],answer:'B',explanation:'Find two numbers that multiply to 6 and add to 5. Those are 2 and 3. So (x + 2)(x + 3).',memory_hook:'For x² + bx + c, find two numbers that × to c and + to b. Here: 2×3=6 and 2+3=5. Job done.'},
  {paper:'algebra',topic:'Algebra',q:'Solve the simultaneous equations: x + y = 10 and x − y = 4.',options:['A. x = 6, y = 4','B. x = 7, y = 3','C. x = 8, y = 2','D. x = 5, y = 5'],answer:'B',explanation:'Adding the equations: 2x = 14, so x = 7. Substituting: 7 + y = 10, so y = 3.',memory_hook:'Add or subtract the equations to eliminate one variable. Here, adding eliminates y and gives 2x = 14.'},
  {paper:'algebra',topic:'Algebra',q:'What is the gradient of the line y = 3x − 5?',options:['A. −5','B. 3','C. 5','D. −3'],answer:'B',explanation:'In the form y = mx + c, m is the gradient. Here m = 3.',memory_hook:'y = mx + c. The number in front of x is always the gradient (m). The constant at the end is the y-intercept (c).'},

  // ─── Geometry ───
  {paper:'geometry',topic:'Geometry',q:'A right-angled triangle has legs of length 6 cm and 8 cm. What is the hypotenuse?',options:['A. 10 cm','B. 11 cm','C. 12 cm','D. 14 cm'],answer:'A',explanation:'a² + b² = c². 6² + 8² = 36 + 64 = 100. √100 = 10.',memory_hook:'Pythagoras: a² + b² = c². The 3-4-5 triple scaled up is 6-8-10. These Pythagorean triples are worth memorising.'},
  {paper:'geometry',topic:'Geometry',q:'What is the area of a circle with radius 5 cm? (Give answer in terms of π)',options:['A. 10π cm²','B. 25π cm²','C. 50π cm²','D. 5π cm²'],answer:'B',explanation:'Area = πr² = π × 5² = 25π cm².',memory_hook:'Area = πr². Radius squared, then multiply by π. Don\'t confuse with circumference (2πr) — area uses r², circumference uses r.'},
  {paper:'geometry',topic:'Geometry',q:'The angles in a triangle are x, 2x, and 3x. What is the value of x?',options:['A. 20°','B. 25°','C. 30°','D. 35°'],answer:'C',explanation:'Angles in a triangle sum to 180°. x + 2x + 3x = 6x = 180°. x = 30°.',memory_hook:'Angles in a triangle always add to 180°. Set up the equation with your angle expressions, add them, set equal to 180°.'},
  {paper:'geometry',topic:'Geometry',q:'What is the volume of a cylinder with radius 3 cm and height 10 cm? (in terms of π)',options:['A. 30π cm³','B. 60π cm³','C. 90π cm³','D. 180π cm³'],answer:'C',explanation:'Volume = πr²h = π × 9 × 10 = 90π cm³.',memory_hook:'Cylinder volume = area of circle × height = πr²h. It\'s just a stack of circles — find one circle\'s area then multiply by how tall the stack is.'},
  {paper:'geometry',topic:'Geometry',q:'Two parallel lines are cut by a transversal. Which angle pair is always equal?',options:['A. Co-interior angles','B. Supplementary angles','C. Alternate angles','D. Obtuse angles'],answer:'C',explanation:'Alternate angles (Z-angles) are always equal when lines are parallel. Co-interior angles add up to 180° instead.',memory_hook:'Alternate angles make a Z shape between the parallel lines — spot the Z and you know those angles are equal.'},

  // ─── Statistics ───
  {paper:'statistics',topic:'Statistics',q:'Find the median of: 3, 7, 2, 9, 5.',options:['A. 5','B. 6','C. 7','D. 3'],answer:'A',explanation:'Arrange in order: 2, 3, 5, 7, 9. The middle value (3rd of 5) is 5.',memory_hook:'Median = middle value. First sort the list, then find the middle. For an even number of values, average the two middle ones.'},
  {paper:'statistics',topic:'Statistics',q:'A bag contains 3 red and 7 blue balls. What is the probability of picking a red ball?',options:['A. 3/7','B. 3/10','C. 7/10','D. 1/3'],answer:'B',explanation:'Probability = favourable outcomes ÷ total outcomes = 3 ÷ (3 + 7) = 3/10.',memory_hook:'P(event) = number of ways it can happen ÷ total number of outcomes. Count reds (3) over total (10).'},
  {paper:'statistics',topic:'Statistics',q:'What does the interquartile range (IQR) measure?',options:['A. The difference between the largest and smallest values','B. The spread of the middle 50% of data','C. The average of the data','D. The most frequent value'],answer:'B',explanation:'IQR = Q3 − Q1, which measures the spread of the central 50% of values, ignoring outliers.',memory_hook:'IQR = the middle half\'s spread. Q3 − Q1. It\'s better than the full range because it ignores extreme values at the ends.'},
  {paper:'statistics',topic:'Statistics',q:'In a frequency table, how do you calculate the estimated mean?',options:['A. Add all frequencies together','B. Divide the highest value by the number of groups','C. Calculate Σ(midpoint × frequency) ÷ Σfrequency','D. Find the middle frequency'],answer:'C',explanation:'Multiply each group\'s midpoint by its frequency, sum those products, then divide by the total frequency.',memory_hook:'Estimated mean = Σ(fx) ÷ Σf. For each group: midpoint × frequency. Add them all up. Divide by total frequency. Same as a weighted average.'},
];
