const ALL_Q = [
  {paper:'p1',topic:'CPU Architecture',q:'What does the ALU in a CPU do?',options:['A. Stores the current instruction being executed','B. Performs arithmetic and logical operations','C. Controls the flow of data between CPU components','D. Holds the address of the next instruction'],answer:'B',explanation:'The Arithmetic Logic Unit carries out calculations (like addition) and logical comparisons (like greater than). It is the maths brain of the CPU.',memory_hook:'Think of the ALU as a calculator bolted inside the CPU — it does all the sums and yes/no decisions.'},
  {paper:'p1',topic:'CPU Architecture',q:'Which register holds the address of the next instruction to be fetched?',options:['A. Accumulator','B. Memory Data Register','C. Program Counter','D. Memory Address Register'],answer:'C',explanation:'The Program Counter keeps track of where the CPU is in the program by storing the address of the next instruction to fetch.',memory_hook:'The Program Counter is like a bookmark — it always points to the next page the CPU needs to read.'},
  {paper:'p1',topic:'CPU Architecture',q:'What is the correct order of the fetch-execute cycle?',options:['A. Execute, Fetch, Decode','B. Decode, Fetch, Execute','C. Fetch, Decode, Execute','D. Fetch, Execute, Decode'],answer:'C',explanation:'The CPU first fetches the instruction from memory, decodes it to understand what to do, then executes it. This repeats continuously.',memory_hook:'FDE — "Fetch Dinner Early". Fetch it, figure out what it is, then eat it.'},
  {paper:'p1',topic:'CPU Performance',q:'Which of the following would most directly increase CPU performance?',options:['A. Increasing RAM capacity','B. Increasing clock speed','C. Adding more storage','D. Using a larger monitor'],answer:'B',explanation:'Clock speed determines how many instruction cycles the CPU can complete per second. A higher clock speed means more instructions processed each second.',memory_hook:'Clock speed is like the tempo of a metronome — the faster it ticks, the more work the CPU does in the same time.'},
  {paper:'p1',topic:'CPU Performance',q:'How does increasing the number of CPU cores improve performance?',options:['A. It increases the clock speed of each core','B. It allows multiple tasks to be processed simultaneously','C. It increases the size of the cache','D. It reduces the amount of RAM needed'],answer:'B',explanation:'Multiple cores allow the CPU to handle several tasks or threads at the same time, improving overall performance for multitasking.',memory_hook:'Cores are like checkout lanes in a supermarket — more lanes means more customers served at the same time.'},
  {paper:'p1',topic:'Memory',q:'What is the main difference between RAM and ROM?',options:['A. RAM is permanent; ROM is temporary','B. RAM is volatile; ROM is non-volatile','C. RAM is slower than ROM','D. ROM can be written to freely; RAM cannot'],answer:'B',explanation:'RAM loses its contents when power is removed (volatile), while ROM retains data permanently without power (non-volatile).',memory_hook:'RAM is like a whiteboard — wipe it when the power goes. ROM is like text carved in stone — it stays forever.'},
  {paper:'p1',topic:'Memory',q:'What is cache memory used for?',options:['A. Long-term storage of files','B. Storing frequently used instructions close to the CPU for fast access','C. Running the operating system','D. Storing the BIOS'],answer:'B',explanation:'Cache is a small, very fast memory between the CPU and RAM that stores frequently accessed data so the CPU does not have to wait for slower RAM.',memory_hook:'Cache is like keeping your most-used pens on your desk rather than walking to a cupboard every time — it saves time.'},
  {paper:'p1',topic:'Storage',q:'Which type of storage uses magnetism to store data?',options:['A. SSD','B. USB flash drive','C. Hard disk drive','D. Optical disc'],answer:'C',explanation:'Hard disk drives (HDDs) store data by magnetising tiny areas on spinning platters. SSDs and USB drives use flash memory instead.',memory_hook:'An HDD is like a vinyl record player — spinning disc, read head moves across it — except it stores your files instead of music.'},
  {paper:'p1',topic:'Storage',q:'What is one advantage of an SSD over an HDD?',options:['A. SSDs are cheaper per gigabyte','B. SSDs have faster read and write speeds','C. SSDs can store more data','D. SSDs last longer in all conditions'],answer:'B',explanation:'SSDs have no moving parts and use flash memory, which allows much faster data access than the spinning platters and moving read heads of an HDD.',memory_hook:'SSD vs HDD — flash memory is instant like a camera flash; spinning disks have to physically spin to the right spot first.'},
  {paper:'p1',topic:'Networks',q:'What does a router do in a network?',options:['A. Converts digital signals to analogue','B. Directs data packets between networks','C. Connects devices within a single LAN using cables','D. Amplifies the wifi signal'],answer:'B',explanation:'A router directs packets of data between different networks, choosing the best path for the data to travel.',memory_hook:'A router is like a postman who reads addresses and decides which road each letter should go down.'},
  {paper:'p1',topic:'Networks',q:'Which network topology connects every device to a central switch or hub?',options:['A. Bus','B. Ring','C. Mesh','D. Star'],answer:'D',explanation:'In a star topology all devices connect to a central switch. If one cable fails, only that device is affected — the rest keep working.',memory_hook:'Draw it and it literally looks like a star — one centre point with lines radiating outward to each device.'},
  {paper:'p1',topic:'Networks',q:'What is the difference between a LAN and a WAN?',options:['A. LANs use wireless; WANs use cables','B. LANs cover a small area; WANs cover a large geographical area','C. LANs are faster than WANs in all cases','D. WANs are privately owned; LANs are public'],answer:'B',explanation:'A LAN (Local Area Network) covers a small area like a school or office. A WAN (Wide Area Network) spans large distances, like the internet.',memory_hook:'LAN = Local (your street). WAN = Wide (the whole world). Think of LAN as a village and WAN as the motorway connecting all villages.'},
  {paper:'p1',topic:'Network Protocols',q:'What is the purpose of HTTP?',options:['A. Sending emails between servers','B. Transferring web pages between a server and browser','C. Encrypting data during transmission','D. Assigning IP addresses to devices'],answer:'B',explanation:'HTTP (HyperText Transfer Protocol) defines how web browsers request pages and how web servers respond and send them back.',memory_hook:'HTTP is the language your browser uses to ask a website "can I have that page please?" — and the website replies with the content.'},
  {paper:'p1',topic:'Network Protocols',q:'What does DNS do?',options:['A. Encrypts data sent over a network','B. Translates domain names into IP addresses','C. Assigns IP addresses to devices automatically','D. Compresses web page data for faster loading'],answer:'B',explanation:'The Domain Name System converts human-readable domain names (like google.com) into numerical IP addresses that computers use to find each other.',memory_hook:'DNS is the internet\'s phone book — you look up a name (google.com) and it gives you the number (IP address) to call.'},
  {paper:'p1',topic:'Network Security',q:'What is a brute force attack?',options:['A. Tricking users into revealing passwords','B. Trying every possible password combination until one works','C. Intercepting data packets on a network','D. Installing hidden software to record keystrokes'],answer:'B',explanation:'A brute force attack systematically tries all possible combinations of characters until the correct password is found.',memory_hook:'Brute force is like trying every key on a giant keyring one by one until the door opens — slow but eventually it works.'},
  {paper:'p1',topic:'Network Security',q:'Which of the following best describes phishing?',options:['A. Flooding a server with requests to make it crash','B. Encrypting a victim\'s files and demanding payment','C. Sending fake emails to trick users into revealing personal information','D. Exploiting a software bug to gain unauthorised access'],answer:'C',explanation:'Phishing involves fraudulent messages (usually emails) that impersonate trusted sources to steal passwords or personal data.',memory_hook:'Phishing sounds like "fishing" — criminals cast out fake emails as bait, hoping someone takes the hook.'},
  {paper:'p1',topic:'Network Security',q:'What does encryption do to data?',options:['A. Deletes data that is no longer needed','B. Compresses data to reduce file size','C. Scrambles data so only authorised parties can read it','D. Backs up data to a remote server'],answer:'C',explanation:'Encryption converts data into a scrambled format using a key. Only someone with the correct key can decrypt and read the original data.',memory_hook:'Encryption is like writing a message in a secret code — even if someone intercepts it, it\'s gibberish without the key.'},
  {paper:'p1',topic:'Systems Software',q:'What is the main role of an operating system?',options:['A. To provide antivirus protection','B. To manage hardware resources and provide an interface for users','C. To compress files to save storage space','D. To connect the computer to the internet'],answer:'B',explanation:'The OS manages the CPU, memory, storage and input/output devices, and provides the user interface and environment for running applications.',memory_hook:'The OS is like the manager of a busy office — it decides who gets the desk, the printer, and the phone at any given time.'},
  {paper:'p1',topic:'Systems Software',q:'What does defragmentation do to a hard drive?',options:['A. Deletes temporary files to free up space','B. Scans for and removes viruses','C. Rearranges fragmented files so they are stored contiguously','D. Compresses files to reduce their size'],answer:'C',explanation:'Over time files get split into fragments across the disk. Defragmentation reorganises these so each file is stored in one continuous block, speeding up access.',memory_hook:'Defrag is like tidying a messy bookshelf — putting all chapters of the same book together so you don\'t have to hunt around.'},
  {paper:'p1',topic:'Ethical Impacts',q:'Which law in the UK protects personal data stored by organisations?',options:['A. Computer Misuse Act','B. Copyright Design and Patents Act','C. Data Protection Act','D. Freedom of Information Act'],answer:'C',explanation:'The Data Protection Act (and UK GDPR) sets rules for how organisations collect, store and use personal data, giving individuals rights over their information.',memory_hook:'Data Protection Act = your personal info has a bodyguard. Companies can\'t just do whatever they want with it.'},
  {paper:'p1',topic:'Ethical Impacts',q:'What does the Computer Misuse Act 1990 make illegal?',options:['A. Copying music without permission','B. Unauthorised access to computer systems','C. Selling personal data to third parties','D. Using social media under the age of 13'],answer:'B',explanation:'The Computer Misuse Act criminalises hacking, introducing malware, and any unauthorised access to or modification of computer systems.',memory_hook:'Computer Misuse Act = no trespassing in someone else\'s computer. Breaking in, even virtually, is a crime.'},
  {paper:'p1',topic:'Binary',q:'What is 0101 in denary?',options:['A. 3','B. 4','C. 5','D. 6'],answer:'C',explanation:'Reading from right to left the binary column values are 1, 2, 4, 8. So 0101 = 0+4+0+1 = 5.',memory_hook:'Binary columns are 8,4,2,1 from left to right — just add up the columns that have a 1. 0101 = 4+1 = 5.'},
  {paper:'p1',topic:'Binary',q:'What is 13 in binary?',options:['A. 1011','B. 1101','C. 1110','D. 1001'],answer:'B',explanation:'13 = 8+4+1, so the bits for 8, 4 and 1 are 1, giving 1101.',memory_hook:'Work right to left: does 13 need a 1? Yes (13-1=12). Does 12 need a 2? No. Does 12 need a 4? Yes (12-4=8). Does 8 need an 8? Yes. So 1101.'},
  {paper:'p2',topic:'Algorithms',q:'What does an algorithm need to be to be considered correct?',options:['A. Written in a programming language','B. Able to run on any computer','C. A clear set of steps that always produces the correct output for valid inputs','D. Stored in a flowchart'],answer:'C',explanation:'An algorithm is a precise, finite sequence of steps. It must produce the correct result for all valid inputs to be considered correct.',memory_hook:'A recipe is a great analogy — if you follow the steps exactly and get edible food every time, it\'s a correct recipe (algorithm).'},
  {paper:'p2',topic:'Algorithms',q:'Which searching algorithm works by repeatedly halving the search space?',options:['A. Linear search','B. Binary search','C. Bubble sort','D. Merge sort'],answer:'B',explanation:'Binary search works on sorted lists by checking the middle element, then eliminating the half where the target cannot be, repeating until found.',memory_hook:'Binary search is like guessing a number 1-100 — always guess the middle. "Higher" or "lower" halves your options every time.'},
  {paper:'p2',topic:'Algorithms',q:'In a bubble sort, what happens in each pass through the list?',options:['A. The list is split in half','B. Adjacent elements are compared and swapped if out of order','C. The smallest element is moved to the front','D. Elements are inserted into their correct position one at a time'],answer:'B',explanation:'Bubble sort repeatedly compares neighbouring pairs and swaps them if they are in the wrong order. Larger values bubble towards the end with each pass.',memory_hook:'Imagine bubbles rising in a fizzy drink — the biggest values rise to the top (end of list) first, one pass at a time.'},
  {paper:'p2',topic:'Algorithms',q:'What is the advantage of binary search over linear search?',options:['A. Binary search works on unsorted lists','B. Binary search is faster on large sorted lists','C. Binary search uses less memory','D. Binary search always finds the item in one step'],answer:'B',explanation:'Binary search eliminates half the remaining data each step, making it much faster than linear search which checks every item one by one on large lists.',memory_hook:'Linear search = checking every seat in a stadium. Binary search = going to the middle, then the middle of the half where your seat is.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the output of this Python code?\n\nx = 10\ny = 3\nprint(x % y)',options:['A. 3','B. 3.33','C. 1','D. 0'],answer:'C',explanation:'The % operator gives the remainder after division. 10 divided by 3 is 3 remainder 1, so the output is 1.',memory_hook:'% is the "leftovers" operator — 10 ÷ 3 = 3 with 1 left over. % gives you just the leftover.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'Which of the following is a valid OCR ERL for loop that runs 5 times?',options:['A. for i = 1 to 5 do','B. for i = 0 to 4','C. repeat i from 0 to 5','D. loop i = 0 while i < 5'],answer:'B',explanation:'In OCR ERL, for loops use the syntax "for i = start to end" and are inclusive of both values. 0 to 4 gives exactly 5 iterations: 0,1,2,3,4.',memory_hook:'OCR ERL counts inclusively — "for i = 0 to 4" means 0,1,2,3,4 which is five numbers. Don\'t be tricked into writing "to 5"!'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is a variable?',options:['A. A fixed value that cannot change during a program','B. A named memory location that stores a value which can change','C. A block of reusable code','D. A type of loop'],answer:'B',explanation:'A variable is a named storage location in memory. The value it holds can be read and changed during program execution.',memory_hook:'A variable is like a labelled box — you give it a name, put a value inside, and you can swap out the contents whenever you like.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does this OCR ERL code output?\n\nfor i = 1 to 3\n  print(i)\nnext i',options:['A. 1 2 3 4','B. 0 1 2 3','C. 1 2 3','D. 0 1 2'],answer:'C',explanation:'The loop runs from 1 to 3 inclusive, printing i each time, outputting 1, then 2, then 3.',memory_hook:'The loop starts at 1 and stops at 3 — it prints every number it visits, so 1, 2, 3. Simple!'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the output of this Python?\n\nfor i in range(3):\n    print(i)',options:['A. 1 2 3','B. 0 1 2','C. 0 1 2 3','D. 1 2'],answer:'B',explanation:'range(3) in Python produces 0, 1, 2 — it starts at 0 and goes up to but NOT including 3.',memory_hook:'Python\'s range() starts at 0 and stops BEFORE the number you give it. range(3) = 0,1,2. Think of it as "up to but not touching 3".'},
  {paper:'p2',topic:'Robust Programs',q:'What is input validation?',options:['A. Checking that a program runs without errors','B. Ensuring user input meets expected criteria before processing','C. Removing bugs from code','D. Testing a program with extreme values'],answer:'B',explanation:'Input validation checks that data entered by a user is of the correct type, range, or format before the program uses it.',memory_hook:'Validation is like a bouncer at a club — it checks your credentials at the door before letting data into the program.'},
  {paper:'p2',topic:'Robust Programs',q:'What type of test data would you use to check a program correctly rejects invalid input?',options:['A. Normal data','B. Boundary data','C. Erroneous data','D. Extreme data'],answer:'C',explanation:'Erroneous data is input that is completely the wrong type or format (e.g. entering "hello" for an age field). The program should reject it gracefully.',memory_hook:'Erroneous = deliberately terrible data. You\'re trying to break it on purpose to make sure it doesn\'t break accidentally later.'},
  {paper:'p2',topic:'Robust Programs',q:'What is the purpose of a function (subroutine) in programming?',options:['A. To slow down the program for testing','B. To store data permanently','C. To group reusable code that can be called multiple times','D. To connect to external databases'],answer:'C',explanation:'Functions allow you to write a block of code once and call it whenever needed, reducing repetition and making programs easier to maintain.',memory_hook:'A function is like a vending machine — build it once, press the button (call it) whenever you need it, get a result every time.'},
  {paper:'p2',topic:'Boolean Logic',q:'What is the output of: True AND False?',options:['A. True','B. False','C. 1','D. None'],answer:'B',explanation:'AND returns True only when BOTH inputs are True. Since one input is False, the result is False.',memory_hook:'AND is strict — BOTH sides must be True. Think of a two-key safe that only opens when both keys turn simultaneously.'},
  {paper:'p2',topic:'Boolean Logic',q:'What does a NOT gate do?',options:['A. Outputs True only if both inputs are True','B. Outputs True if at least one input is True','C. Reverses the input — True becomes False and vice versa','D. Outputs True only if inputs are different'],answer:'C',explanation:'A NOT gate inverts the input. True becomes False and False becomes True.',memory_hook:'NOT is the "opposite day" gate — whatever goes in, the opposite comes out. Simple as that.'},
  {paper:'p2',topic:'Boolean Logic',q:'What is the result of: True OR False?',options:['A. True','B. False','C. Depends on context','D. Error'],answer:'A',explanation:'OR returns True if at least one input is True. Since one input is True here, the result is True.',memory_hook:'OR is generous — only ONE side needs to be True. Think of it as "either will do".'},
  {paper:'p2',topic:'Programming Languages',q:'What is the difference between a compiler and an interpreter?',options:['A. A compiler runs code line by line; an interpreter translates it all at once','B. A compiler translates the whole program before running; an interpreter translates and runs line by line','C. A compiler only works with Python; an interpreter works with all languages','D. There is no difference'],answer:'B',explanation:'A compiler translates the entire source code into machine code before execution. An interpreter translates and executes one line at a time.',memory_hook:'Compiler = translate the whole book before reading it. Interpreter = translate one sentence, read it, translate the next.'},
  {paper:'p2',topic:'Algorithms',q:'What is decomposition in computational thinking?',options:['A. Writing code in smaller functions','B. Breaking a complex problem into smaller, more manageable sub-problems','C. Removing unnecessary steps from an algorithm','D. Converting a flowchart into code'],answer:'B',explanation:'Decomposition means breaking a large problem down into smaller parts that are easier to understand, solve and code separately.',memory_hook:'Decomposition is like eating a pizza — you don\'t shove the whole thing in your mouth, you break it into slices first.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the correct Python syntax to get input from a user and store it?',options:['A. name = scan("Enter name")','B. name = input("Enter name")','C. name = get("Enter name")','D. input name = "Enter name"'],answer:'B',explanation:'In Python, the input() function displays a prompt and waits for the user to type something, returning it as a string.',memory_hook:'input() in Python is just like asking a question out loud — you give it the prompt text, and the user types their answer back.'},
  {paper:'p2',topic:'Robust Programs',q:'What is authentication used for in a program?',options:['A. To speed up program execution','B. To verify the identity of a user before granting access','C. To compress data for storage','D. To check code for syntax errors'],answer:'B',explanation:'Authentication verifies that a user is who they claim to be, typically through passwords, PINs, or biometrics, before granting access to a system.',memory_hook:'Authentication = proving you are who you say you are. Like showing ID at the door before you\'re let in.'}

  
  // ─── PAPER 1: CPU Architecture ───
  {paper:'p1',topic:'CPU Architecture',q:'What is stored in the Memory Data Register (MDR)?',options:['A. The address of the next instruction','B. The data being transferred to or from memory','C. The result of the last calculation','D. The current instruction being decoded'],answer:'B',explanation:'The MDR holds data that has just been read from, or is about to be written to, memory. It acts as a buffer between the CPU and RAM.',memory_hook:'MDR = Memory Data Register = the delivery box. Whatever is being sent to or received from memory sits in this box temporarily.'},
  {paper:'p1',topic:'CPU Architecture',q:'What is the role of the Memory Address Register (MAR)?',options:['A. It stores the result of arithmetic operations','B. It holds the address in memory that the CPU wants to read from or write to','C. It decodes instructions','D. It stores the current instruction'],answer:'B',explanation:'The MAR holds the memory address that the CPU needs to access, telling RAM exactly where to read from or write to.',memory_hook:'MAR = the postcode. Before the CPU can fetch data, it writes the address (postcode) in the MAR so RAM knows where to look.'},
  {paper:'p1',topic:'CPU Architecture',q:'What does the Control Unit (CU) do?',options:['A. Performs calculations on data','B. Stores frequently used data','C. Coordinates and controls the activities of the CPU','D. Transfers data to secondary storage'],answer:'C',explanation:'The Control Unit manages the fetch-decode-execute cycle, sending control signals to coordinate all parts of the CPU and computer system.',memory_hook:'The CU is the CPU\'s conductor — it doesn\'t play an instrument itself but tells everyone else when and what to play.'},
  {paper:'p1',topic:'CPU Architecture',q:'What is the Accumulator?',options:['A. A register that stores the result of calculations performed by the ALU','B. The part of the CPU that fetches instructions','C. A type of cache memory','D. A component that controls input and output'],answer:'A',explanation:'The Accumulator is a register in the CPU that temporarily stores the result of arithmetic and logic operations performed by the ALU.',memory_hook:'Accumulate means to gather — the Accumulator gathers up the result of each calculation the ALU performs.'},

  // ─── PAPER 1: CPU Performance ───
  {paper:'p1',topic:'CPU Performance',q:'What is cache memory and how does it affect CPU performance?',options:['A. It is slow memory that stores the operating system','B. It is fast memory close to the CPU that reduces the time spent waiting for data from RAM','C. It is a type of secondary storage','D. It stores the fetch-execute cycle instructions permanently'],answer:'B',explanation:'Cache is a small, very fast memory built close to or into the CPU. Frequently used data is stored there so the CPU spends less time waiting for slower RAM.',memory_hook:'Cache is like a mini-fridge in your room — the big fridge (RAM) is downstairs but you keep the most-needed snacks close by for speed.'},
  {paper:'p1',topic:'CPU Performance',q:'Why does a higher clock speed not always mean better overall performance?',options:['A. Higher clock speeds use less electricity','B. Other factors like number of cores and cache size also affect performance','C. Clock speed only affects the ALU','D. Higher clock speeds reduce the number of cores'],answer:'B',explanation:'Performance depends on clock speed, number of cores, cache size, and other factors. A CPU with a lower clock speed but more cores may outperform one with just a higher clock speed.',memory_hook:'A fast drummer in a band doesn\'t help if the guitarists can\'t keep up — all parts of the system need to work together.'},

  // ─── PAPER 1: Embedded Systems ───
  {paper:'p1',topic:'Embedded Systems',q:'What is an embedded system?',options:['A. A computer system built into a device to control a specific function','B. A type of operating system used in servers','C. A program stored on a CD-ROM','D. A network of computers sharing resources'],answer:'A',explanation:'An embedded system is a computer (processor + memory + software) built into a larger device to perform a dedicated function, like controlling a washing machine.',memory_hook:'Embedded = hidden inside. The computer is embedded (hidden) inside the device, quietly controlling it without you seeing it.'},
  {paper:'p1',topic:'Embedded Systems',q:'Which of the following is an example of an embedded system?',options:['A. A desktop PC running Windows','B. A smartphone app store','C. The control system inside a microwave oven','D. A cloud storage service'],answer:'C',explanation:'A microwave oven contains a microprocessor that controls timing, power levels and display — a dedicated computer embedded inside the appliance.',memory_hook:'Your microwave has a brain — it\'s just hidden inside the plastic. That hidden brain is an embedded system.'},
  {paper:'p1',topic:'Embedded Systems',q:'What is a key characteristic of most embedded systems?',options:['A. They run general-purpose software like word processors','B. They perform a specific, fixed task and rarely need updating','C. They always have a keyboard and screen','D. They require a fast internet connection'],answer:'B',explanation:'Embedded systems are typically designed to do one job reliably — like controlling a car\'s ABS brakes — and rarely need software updates.',memory_hook:'An embedded system is a specialist, not a generalist. It does ONE thing brilliantly and doesn\'t get distracted.'},

  // ─── PAPER 1: Memory & Storage ───
  {paper:'p1',topic:'Memory',q:'A computer has 8GB of RAM. What does this primarily affect?',options:['A. How fast data is written to the hard drive','B. How many programs can run simultaneously without slowing down','C. The resolution of the screen','D. The speed of the internet connection'],answer:'B',explanation:'More RAM allows more programs and data to be held in fast memory at once, reducing the need to swap data to slower storage and keeping the system running smoothly.',memory_hook:'RAM is your desk space — more desk = more things you can have open at once without knocking things on the floor.'},
  {paper:'p1',topic:'Storage',q:'What is the main purpose of secondary storage?',options:['A. To process data faster than RAM','B. To permanently store data when the computer is switched off','C. To connect the CPU to peripherals','D. To manage the fetch-execute cycle'],answer:'B',explanation:'Secondary storage (like HDDs, SSDs, or optical discs) provides permanent, non-volatile storage so data and programs are retained when the power is off.',memory_hook:'Secondary storage is your filing cabinet — everything stays there even when you go home for the night (power off).'},
  {paper:'p1',topic:'Storage',q:'What is the difference between primary and secondary storage?',options:['A. Primary storage is permanent; secondary storage is temporary','B. Primary storage is directly accessible by the CPU; secondary storage is not','C. Secondary storage is faster than primary storage','D. Primary storage is larger than secondary storage'],answer:'B',explanation:'Primary storage (RAM, cache, registers) is directly accessible by the CPU and fast but volatile. Secondary storage (HDD, SSD) is permanent but slower and accessed via the bus.',memory_hook:'Primary = on the CPU\'s desk (fast, direct). Secondary = in the filing room (slower, you have to go and fetch it).'},
  {paper:'p1',topic:'Storage',q:'Which storage medium uses pits and lands read by a laser?',options:['A. Hard disk drive','B. SSD','C. Optical disc','D. USB flash drive'],answer:'C',explanation:'Optical discs (CDs, DVDs, Blu-rays) store data as microscopic pits and lands (flat areas) on their surface, which are read by a laser beam.',memory_hook:'Optical = light. A laser beam bounces off the disc\'s surface — pits and lands reflect differently, encoding 0s and 1s.'},
  {paper:'p1',topic:'Storage',q:'What is cloud storage?',options:['A. Storage built into the CPU','B. Storing data on remote servers accessed via the internet','C. A type of RAM that never loses data','D. Compressing files to save local disk space'],answer:'B',explanation:'Cloud storage means your files are stored on servers maintained by a company (like Google or Microsoft) and accessed over the internet from any device.',memory_hook:'The cloud is just someone else\'s computer. Your files live on their servers, and you access them via the internet.'},

  // ─── PAPER 1: Data Representation ───
  {paper:'p1',topic:'Binary & Hex',q:'What is 1010 in denary?',options:['A. 8','B. 9','C. 10','D. 12'],answer:'C',explanation:'Binary 1010 = 1×8 + 0×4 + 1×2 + 0×1 = 8 + 2 = 10.',memory_hook:'Columns are 8,4,2,1. Circle the columns with a 1: 8 and 2. Add them: 10. Simple!'},
  {paper:'p1',topic:'Binary & Hex',q:'What is 255 in binary?',options:['A. 11110000','B. 11111110','C. 11111111','D. 10101010'],answer:'C',explanation:'255 = 128+64+32+16+8+4+2+1, so all 8 bits are 1: 11111111.',memory_hook:'255 is the maximum value of a single byte — all 8 bits switched on. Like a light switch panel with every switch flipped up.'},
  {paper:'p1',topic:'Binary & Hex',q:'Convert the hexadecimal number A3 to denary.',options:['A. 153','B. 163','C. 143','D. 173'],answer:'B',explanation:'A in hex = 10, 3 in hex = 3. A3 = (10×16) + 3 = 160 + 3 = 163.',memory_hook:'Hex is base 16. A=10, B=11...F=15. For A3: A is in the 16s column (10×16=160), 3 is in the 1s column. 160+3=163.'},
  {paper:'p1',topic:'Binary & Hex',q:'Why is hexadecimal commonly used in computing?',options:['A. Computers process hex directly','B. It is a compact way to represent binary that is easier for humans to read','C. Hex uses fewer digits than denary','D. Hex is used because it has 16 letters'],answer:'B',explanation:'Each hex digit represents exactly 4 bits, so long binary strings can be written much more compactly and are easier for humans to read and remember.',memory_hook:'FF in hex = 11111111 in binary = 255 in denary. Two characters vs eight — hex is a shorthand for binary that humans can actually read.'},
  {paper:'p1',topic:'Binary & Hex',q:'What is the result of adding binary 0110 + 0101?',options:['A. 1010','B. 1011','C. 1100','D. 1001'],answer:'B',explanation:'0110 (6) + 0101 (5) = 11 in denary = 1011 in binary.',memory_hook:'Convert to denary first if unsure: 6+5=11. Then convert 11 back: 8+2+1 = 1011. Check your working!'},
  {paper:'p1',topic:'Binary & Hex',q:'What is a bit?',options:['A. A group of 8 binary digits','B. A single binary digit, either 0 or 1','C. A unit of storage equal to 1000 bytes','D. The smallest addressable unit of memory'],answer:'B',explanation:'A bit is the smallest unit of data in computing — a single binary digit that can be either 0 or 1.',memory_hook:'Bit = Binary digIT. Just one switch — off (0) or on (1). Everything in a computer is built from billions of these tiny switches.'},
  {paper:'p1',topic:'Binary & Hex',q:'How many bytes are in a kilobyte (KB)?',options:['A. 100','B. 512','C. 1000 or 1024 depending on context','D. 8'],answer:'C',explanation:'In decimal (SI) a kilobyte is 1000 bytes. In binary (computing) a kibibyte is 1024 bytes. Both usages are common — context matters.',memory_hook:'1KB ≈ 1000 bytes. Think of it as roughly a thousand characters of text — about half a page of typing.'},
  {paper:'p1',topic:'Binary & Hex',q:'What is the denary value of the hexadecimal number FF?',options:['A. 240','B. 250','C. 255','D. 256'],answer:'C',explanation:'F in hex = 15. FF = (15×16) + 15 = 240 + 15 = 255.',memory_hook:'FF is the highest two-digit hex number — and 255 is the max value of a byte (8 bits all set to 1). They always go together.'},

  // ─── PAPER 1: Data Compression ───
  {paper:'p1',topic:'Data Representation',q:'What is the purpose of data compression?',options:['A. To encrypt data so it cannot be read','B. To reduce the file size so it takes less storage or transmits faster','C. To convert data from binary to hexadecimal','D. To back up data to a remote server'],answer:'B',explanation:'Compression reduces file size by encoding data more efficiently, saving storage space and reducing the time and bandwidth needed to transfer files.',memory_hook:'Compression is like vacuum-packing clothes — same clothes, much less space. Unpack (decompress) when you need them again.'},
  {paper:'p1',topic:'Data Representation',q:'What is the difference between lossy and lossless compression?',options:['A. Lossy compression is faster; lossless compression is slower','B. Lossy permanently removes some data; lossless allows perfect reconstruction of the original','C. Lossless is used for images; lossy is used for text','D. There is no difference'],answer:'B',explanation:'Lossy compression (e.g. JPEG, MP3) permanently discards some data to achieve smaller files. Lossless compression (e.g. PNG, ZIP) allows the exact original to be reconstructed.',memory_hook:'Lossy = you lose some quality forever (like throwing away puzzle pieces). Lossless = everything is kept, just packed more cleverly.'},
  {paper:'p1',topic:'Data Representation',q:'Which file format uses lossy compression?',options:['A. PNG','B. BMP','C. MP3','D. WAV'],answer:'C',explanation:'MP3 uses lossy compression, discarding audio frequencies that humans are less likely to notice, significantly reducing file size compared to uncompressed WAV.',memory_hook:'MP3 tricks your ears — it throws away sounds you probably won\'t notice missing. WAV keeps everything, so it\'s much bigger.'},

  // ─── PAPER 1: Networks ───
  {paper:'p1',topic:'Networks',q:'What is packet switching?',options:['A. Sending an entire file as one continuous stream','B. Breaking data into packets that travel independently and are reassembled at the destination','C. A method of encrypting network traffic','D. A type of network topology'],answer:'B',explanation:'Packet switching breaks data into small packets, each of which can take different routes across the network and are reassembled in the correct order at the destination.',memory_hook:'Packet switching is like sending a book one page at a time — each page takes the fastest available road, and the reader sorts the pages at the end.'},
  {paper:'p1',topic:'Networks',q:'What does IP stand for and what is its purpose?',options:['A. Internet Protocol — it defines rules for addressing and routing data across networks','B. Internal Processor — it manages CPU tasks','C. Input Program — it handles keyboard input','D. Integrated Port — it connects hardware devices'],answer:'A',explanation:'IP (Internet Protocol) defines how data is addressed and routed between devices on a network using unique IP addresses.',memory_hook:'IP addresses are like postal addresses for computers — every device has one so data knows where to go.'},
  {paper:'p1',topic:'Networks',q:'What is the purpose of a MAC address?',options:['A. To identify the software running on a device','B. To uniquely identify a network interface card at the hardware level','C. To assign a temporary address for internet browsing','D. To encrypt data on a wireless network'],answer:'B',explanation:'A MAC (Media Access Control) address is a unique hardware identifier assigned to every network interface card by the manufacturer.',memory_hook:'MAC address = the device\'s fingerprint. It\'s burned into the hardware at the factory and never changes, unlike an IP address.'},
  {paper:'p1',topic:'Networks',q:'What is the difference between a switch and a hub?',options:['A. A hub sends data only to the intended device; a switch sends to all devices','B. A switch sends data only to the intended device; a hub broadcasts to all devices','C. Switches are wireless; hubs are wired','D. There is no practical difference'],answer:'B',explanation:'A switch is intelligent — it sends data only to the specific device it is intended for. A hub broadcasts data to every connected device, wasting bandwidth.',memory_hook:'Hub = shout in a room (everyone hears). Switch = whisper directly to the right person. Switches are smarter and more private.'},
  {paper:'p1',topic:'Networks',q:'What does HTTPS add compared to HTTP?',options:['A. Faster page loading','B. Encryption of data transferred between browser and server','C. The ability to send emails','D. Automatic compression of web pages'],answer:'B',explanation:'HTTPS uses TLS/SSL encryption to secure the data travelling between your browser and the web server, protecting it from being intercepted.',memory_hook:'The S in HTTPS stands for Secure. It\'s like sending a letter in a locked box instead of a see-through envelope.'},
  {paper:'p1',topic:'Networks',q:'What is Wi-Fi?',options:['A. A type of network cable','B. A wireless networking technology using radio waves','C. A protocol for sending emails','D. A method of encrypting data'],answer:'B',explanation:'Wi-Fi uses radio waves to allow devices to connect to a local area network wirelessly, without needing physical cables.',memory_hook:'Wi-Fi is radio for your data — just like a radio station broadcasts music through the air, Wi-Fi broadcasts data through the air to your devices.'},

  // ─── PAPER 1: Network Security ───
  {paper:'p1',topic:'Network Security',q:'What is malware?',options:['A. A type of network protocol','B. Software designed to damage, disrupt or gain unauthorised access to systems','C. A firewall configuration','D. An encrypted backup system'],answer:'B',explanation:'Malware (malicious software) is any software intentionally designed to cause harm, including viruses, ransomware, spyware and trojans.',memory_hook:'Mal = bad (Latin). Malware = bad software. It\'s any software that wants to do something harmful to your system or data.'},
  {paper:'p1',topic:'Network Security',q:'What is a trojan horse in computing?',options:['A. A virus that copies itself across a network','B. Malware disguised as legitimate software to trick users into installing it','C. A program that monitors and records keystrokes','D. Software that encrypts files and demands payment'],answer:'B',explanation:'A trojan disguises itself as useful software (like a game or tool) to trick users into installing it, then performs malicious actions in the background.',memory_hook:'Just like the Greek myth — it looks like a gift (useful software) but something nasty is hidden inside waiting to cause harm.'},
  {paper:'p1',topic:'Network Security',q:'What is ransomware?',options:['A. Software that displays unwanted adverts','B. A program that monitors your keystrokes','C. Malware that encrypts a victim\'s files and demands payment for the key','D. A virus that deletes files from the hard drive'],answer:'C',explanation:'Ransomware encrypts the victim\'s files, making them inaccessible, then demands a ransom payment (usually cryptocurrency) in exchange for the decryption key.',memory_hook:'Ransom + ware. It holds your files hostage and demands money to release them — like a digital kidnapper.'},
  {paper:'p1',topic:'Network Security',q:'What does a firewall do?',options:['A. Speeds up internet connection','B. Monitors and controls incoming and outgoing network traffic based on rules','C. Encrypts data stored on a hard drive','D. Removes viruses from files'],answer:'B',explanation:'A firewall acts as a barrier between a trusted internal network and untrusted external networks, blocking traffic that does not meet defined security rules.',memory_hook:'A firewall is like a security guard at a building entrance — checking everyone who comes in or goes out and turning away anyone suspicious.'},
  {paper:'p1',topic:'Network Security',q:'What is a DDoS attack?',options:['A. Tricking a user into clicking a malicious link','B. Flooding a server with so many requests it becomes overwhelmed and unavailable','C. Intercepting data packets between two communicating parties','D. Installing spyware on a victim\'s computer'],answer:'B',explanation:'A Distributed Denial of Service attack uses many computers (often a botnet) to flood a server with traffic, overwhelming it and making it unavailable to legitimate users.',memory_hook:'DDoS = Digital traffic jam. Attackers flood the server\'s road with so many cars (requests) that real users can\'t get through.'},
  {paper:'p1',topic:'Network Security',q:'What is two-factor authentication (2FA)?',options:['A. Using two different passwords for the same account','B. Requiring two separate forms of verification to confirm a user\'s identity','C. Encrypting data twice for extra security','D. Having two firewalls protecting a network'],answer:'B',explanation:'2FA requires users to provide two different types of evidence (e.g. password + SMS code) before gaining access, making accounts harder to compromise.',memory_hook:'2FA = two locks on the door. Even if someone steals your key (password), they still can\'t get in without the second lock (e.g. your phone).'},
  {paper:'p1',topic:'Network Security',q:'What is a SQL injection attack?',options:['A. Sending spam emails to trick users','B. Inserting malicious SQL code into a web form to manipulate a database','C. Flooding a server with database requests','D. Stealing a database backup file'],answer:'B',explanation:'SQL injection involves entering malicious database commands into input fields. If the website is not protected, these commands can expose, modify or delete database contents.',memory_hook:'Imagine a form asking for your name and you type "Robert\'; DROP TABLE students;" — if unprotected, the database actually runs that command!'},

  // ─── PAPER 1: Systems Software ───
  {paper:'p1',topic:'Systems Software',q:'What is utility software?',options:['A. Software used to create documents and spreadsheets','B. System software that performs maintenance and optimisation tasks on a computer','C. The interface between the user and the hardware','D. Software that manages network connections'],answer:'B',explanation:'Utility software performs specific tasks to maintain, analyse or optimise a computer, such as antivirus, disk cleanup, backup tools and compression software.',memory_hook:'Utilities = maintenance tools. Just like the utilities in a house (plumber, electrician), utility software fixes and maintains the computer system.'},
  {paper:'p1',topic:'Systems Software',q:'What does an antivirus program do?',options:['A. Speeds up the CPU','B. Detects and removes malicious software from a computer','C. Manages files on secondary storage','D. Controls network access'],answer:'B',explanation:'Antivirus software scans files and programs for known malware signatures and suspicious behaviour, quarantining or removing threats it finds.',memory_hook:'Antivirus is like a doctor for your computer — it checks for infections, identifies the disease (malware), and removes it.'},
  {paper:'p1',topic:'Systems Software',q:'What is the purpose of a backup utility?',options:['A. To compress files for faster transmission','B. To create copies of data so it can be restored if lost or corrupted','C. To delete temporary files and free up space','D. To scan for and remove viruses'],answer:'B',explanation:'Backup utilities automatically copy data to a separate location (external drive, cloud) so that it can be restored if the original is lost, deleted or corrupted.',memory_hook:'A backup is your safety net. If you fall (data loss), the net (backup) catches you and you can get back to where you were.'},
  {paper:'p1',topic:'Systems Software',q:'What is virtual memory?',options:['A. RAM that is built into the CPU','B. A section of secondary storage used as an extension of RAM when RAM is full','C. Memory used exclusively by the operating system','D. A type of cache memory'],answer:'B',explanation:'When RAM is full, the OS uses a section of the hard drive as virtual memory (a swap file), moving less-used data there to free up RAM for active processes.',memory_hook:'Virtual memory is like using your floor as extra desk space when your desk is full — not as convenient, but it keeps you working.'},

  // ─── PAPER 1: Ethical, Legal, Cultural ───
  {paper:'p1',topic:'Ethical Impacts',q:'What does the term "digital divide" refer to?',options:['A. The gap between the processing speed of old and new computers','B. The inequality between those who have access to digital technology and those who do not','C. The difference between digital and analogue signals','D. The split between hardware and software development'],answer:'B',explanation:'The digital divide describes the gap between people who have access to computers and the internet and those who do not, often due to poverty, geography or age.',memory_hook:'Imagine everyone else gets a map to a treasure but some people never receive one — the digital divide is that unfair gap in access.'},
  {paper:'p1',topic:'Ethical Impacts',q:'What is open source software?',options:['A. Software that can only be used on open networks','B. Software whose source code is publicly available for anyone to view, modify and distribute','C. Free software with no licence restrictions','D. Software developed by government organisations'],answer:'B',explanation:'Open source software has its source code made publicly available. Anyone can inspect, modify and distribute it, often leading to community-driven improvements.',memory_hook:'Open source = open kitchen. Anyone can see the recipe, improve it and share their version. Linux and Python are famous examples.'},
  {paper:'p1',topic:'Ethical Impacts',q:'What is the environmental impact of disposing of old computers?',options:['A. Old computers release carbon dioxide when switched off','B. E-waste contains toxic materials that can harm the environment if not properly recycled','C. Disposing of computers increases electromagnetic interference','D. Old computers consume more power when in landfill'],answer:'B',explanation:'Electronic waste (e-waste) contains hazardous substances like lead, mercury and cadmium. If dumped in landfill these can leach into soil and water, causing environmental damage.',memory_hook:'Old electronics = toxic time bombs in landfill. Recycle them properly — the poisons inside (lead, mercury) don\'t just disappear.'},
  {paper:'p1',topic:'Ethical Impacts',q:'What does the Freedom of Information Act allow?',options:['A. Individuals to access personal data held about them by organisations','B. Members of the public to request information held by public bodies','C. Organisations to share personal data freely','D. Journalists to publish any information without restriction'],answer:'B',explanation:'The Freedom of Information Act gives people the right to request information held by public authorities such as government departments, councils and schools.',memory_hook:'FOI = you can ask the council/government "what do you know?" and they generally have to tell you. It makes public bodies transparent.'},
  {paper:'p1',topic:'Ethical Impacts',q:'What is copyright and how does it apply to software?',options:['A. A tax paid for using commercial software','B. The legal right that gives creators control over how their work is used and distributed','C. A certificate proving software has been tested','D. Permission to install software on multiple computers'],answer:'B',explanation:'Copyright law protects the creator\'s work from being copied or distributed without permission. Software is protected by copyright — copying it illegally is piracy.',memory_hook:'Copyright = the creator\'s "right to copy" control. Only they (or those they authorise) can make copies. Pirating software = stealing.'},

  // ─── PAPER 2: Computational Thinking ───
  {paper:'p2',topic:'Computational Thinking',q:'What is abstraction in computational thinking?',options:['A. Writing code in a high-level language','B. Removing unnecessary detail and focusing on the important aspects of a problem','C. Breaking a problem into smaller parts','D. Identifying patterns in data'],answer:'B',explanation:'Abstraction involves stripping away irrelevant details to focus on what matters for solving the problem, making complex problems more manageable.',memory_hook:'A map is a perfect abstraction — it removes details like individual houses and trees, keeping only what you need to navigate.'},
  {paper:'p2',topic:'Computational Thinking',q:'What is pattern recognition in computational thinking?',options:['A. Writing algorithms that sort data','B. Identifying similarities and common features in problems to apply known solutions','C. Converting a problem into pseudocode','D. Testing a program with different inputs'],answer:'B',explanation:'Pattern recognition involves spotting similarities between problems or within data. Recognising a familiar pattern means you can reuse or adapt a known solution.',memory_hook:'Pattern recognition is like noticing all sorting problems share the same structure — once you know bubble sort, you recognise when to use it.'},
  {paper:'p2',topic:'Computational Thinking',q:'What is algorithmic thinking?',options:['A. Writing code without planning','B. Designing a step-by-step solution that can be followed to solve a problem','C. Analysing the output of a program','D. Choosing between different programming languages'],answer:'B',explanation:'Algorithmic thinking means designing a precise, ordered sequence of steps that solves a problem — the kind of thinking needed to create an algorithm.',memory_hook:'Algorithmic thinking = thinking like a recipe writer. You must list every step in the right order so someone else (or a computer) can follow it exactly.'},

  // ─── PAPER 2: Algorithms ───
  {paper:'p2',topic:'Algorithms',q:'What is a flowchart used for in programming?',options:['A. To display the output of a program','B. To visually represent the steps and decisions in an algorithm','C. To test a program for errors','D. To write code in a visual language'],answer:'B',explanation:'Flowcharts use standard symbols (ovals, rectangles, diamonds) to visually map out the logic and flow of an algorithm before coding begins.',memory_hook:'A flowchart is like a map of your algorithm — before you drive (code), you plan the route (flowchart) to make sure you know where you\'re going.'},
  {paper:'p2',topic:'Algorithms',q:'In a flowchart, what shape represents a decision?',options:['A. Rectangle','B. Oval','C. Diamond','D. Parallelogram'],answer:'C',explanation:'A diamond shape represents a decision point (yes/no or true/false question) in a flowchart. It has two exit paths for the two possible answers.',memory_hook:'Diamonds have points going left and right — just like a decision splits the path in two directions (yes this way, no that way).'},
  {paper:'p2',topic:'Algorithms',q:'What does "Big O notation" O(n) mean for a linear search?',options:['A. The algorithm always takes the same time regardless of input size','B. The time taken grows in proportion to the number of items being searched','C. The algorithm takes n² steps','D. The algorithm halves the search space each step'],answer:'B',explanation:'O(n) means the number of steps grows linearly with the input size. Linear search checks each item one by one, so more items = proportionally more time.',memory_hook:'O(n) = one step per item. If you have 100 items it takes 100 steps; 1000 items takes 1000 steps. Straight line relationship.'},
  {paper:'p2',topic:'Algorithms',q:'What is a trace table used for?',options:['A. To plan the structure of a database','B. To manually track variable values through each step of an algorithm to check it works correctly','C. To display the output of a compiled program','D. To measure the execution time of an algorithm'],answer:'B',explanation:'A trace table records the value of each variable at each step of an algorithm, allowing you to manually check the logic and spot errors.',memory_hook:'Trace table = following the footprints. You trace exactly what happens to each variable at every step, like following tracks in the snow.'},
  {paper:'p2',topic:'Algorithms',q:'An algorithm searches a sorted list of 1024 items using binary search. What is the maximum number of comparisons needed?',options:['A. 1024','B. 512','C. 10','D. 32'],answer:'C',explanation:'Binary search halves the search space each step. 2¹⁰ = 1024, so at most 10 comparisons are needed (log₂1024 = 10).',memory_hook:'Binary search halves the list each time. 1024 → 512 → 256 → 128 → 64 → 32 → 16 → 8 → 4 → 2 → 1. Count the arrows: 10 steps.'},
  {paper:'p2',topic:'Algorithms',q:'What is a pre-condition of binary search?',options:['A. The list must contain at least 100 items','B. The list must be sorted','C. The list must contain only numbers','D. The list must be stored in a 2D array'],answer:'B',explanation:'Binary search only works correctly on a sorted list. If the list is unsorted, the algorithm cannot reliably eliminate half the remaining items each step.',memory_hook:'Binary search is like looking up a word in a dictionary — only works because the dictionary is already sorted A-Z. Unsorted = useless.'},
  {paper:'p2',topic:'Algorithms',q:'What is the worst-case scenario for a bubble sort on a list of n items?',options:['A. The list is already sorted','B. The list is sorted in reverse order','C. The list contains duplicate values','D. The list has an odd number of items'],answer:'B',explanation:'Bubble sort is slowest when the list is in reverse order, as every element is in the wrong position and needs to be swapped all the way to its correct location.',memory_hook:'Reverse order = maximum work for bubble sort. Every bubble has to travel the full length of the list. It\'s the worst possible starting point.'},

  // ─── PAPER 2: Programming Fundamentals ───
  {paper:'p2',topic:'Programming Fundamentals',q:'What is a constant in programming?',options:['A. A variable that changes value frequently','B. A named value that is set once and cannot be changed during program execution','C. A function that always returns the same output','D. A loop that runs a fixed number of times'],answer:'B',explanation:'A constant is like a variable but its value is fixed — it is set when the program is written and cannot be changed while the program runs.',memory_hook:'A constant is like pi (3.14159...) — it\'s named, it has a value, but that value NEVER changes no matter what.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the output of this Python code?\n\nx = 5\nif x > 3:\n    print("big")\nelse:\n    print("small")',options:['A. small','B. big','C. 5','D. Error'],answer:'B',explanation:'x is 5, which is greater than 3, so the if condition is True and "big" is printed.',memory_hook:'Work through it: x=5, is 5>3? Yes. So take the if branch and print "big". Always trace through the logic step by step.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What data type would you use to store the value True or False?',options:['A. Integer','B. String','C. Boolean','D. Float'],answer:'C',explanation:'A Boolean data type stores one of two values: True or False. It is used for conditions, flags and logical operations.',memory_hook:'Boolean = binary thinking. Named after mathematician George Boole. Just two options: yes/no, on/off, true/false.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is casting in programming?',options:['A. Sending data over a network','B. Converting a value from one data type to another','C. Declaring a variable for the first time','D. Calling a function with specific parameters'],answer:'B',explanation:'Casting converts a value from one type to another, for example converting the string "42" to the integer 42 using int("42") in Python.',memory_hook:'Casting = changing costume. The value is the same actor but wearing different clothes (data type). int("42") makes "42" dress up as a number.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does the following Python code output?\n\nprint(len("hello"))',options:['A. hello','B. 4','C. 5','D. 6'],answer:'C',explanation:'len() returns the number of characters in a string. "hello" has 5 characters: h, e, l, l, o.',memory_hook:'len() counts the letters. "hello" has 5 letters, so len("hello") = 5. Count them on your fingers if unsure!'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is string concatenation?',options:['A. Converting a string to uppercase','B. Joining two or more strings together','C. Finding the length of a string','D. Splitting a string into a list'],answer:'B',explanation:'Concatenation joins strings together. In Python, "hello" + " " + "world" produces "hello world".',memory_hook:'Concatenate = chain together. Think of linking paper chains — each string snaps onto the next to form one long string.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does this OCR ERL code do?\n\nif score >= 40 then\n  print("Pass")\nelse\n  print("Fail")\nendif',options:['A. Prints "Pass" if score is exactly 40','B. Prints "Pass" if score is 40 or more, otherwise prints "Fail"','C. Prints "Fail" if score is 40 or more','D. Always prints "Pass"'],answer:'B',explanation:'The condition score >= 40 is True for any score of 40 or above. The >= operator means "greater than or equal to".',memory_hook:'>= means "at least". Score >= 40 means "is the score at least 40?" If yes, pass. If no, fail. Just like a real exam threshold!'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the purpose of indentation in Python?',options:['A. To make code look neat for the programmer','B. To define blocks of code that belong together (e.g. inside a loop or function)','C. To add comments to code','D. To indicate that a line is a string'],answer:'B',explanation:'Python uses indentation (whitespace at the start of a line) to define code blocks. Lines at the same indentation level belong to the same block.',memory_hook:'Python\'s indentation is its grammar. Lines that belong inside an if/loop/function must be indented — Python uses spacing, not curly brackets.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the difference between = and == in Python?',options:['A. They are the same operator','B. = assigns a value to a variable; == tests if two values are equal','C. == assigns a value; = tests equality','D. = is used for strings; == is used for numbers'],answer:'B',explanation:'= is the assignment operator (puts a value into a variable). == is the comparison operator (tests whether two values are equal, returning True or False).',memory_hook:'One equals sign (=) is a filling station — it fills a variable. Two equals signs (==) is a weighing scale — it checks if both sides balance.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is a while loop used for?',options:['A. Repeating code a fixed number of times','B. Repeating code as long as a condition remains true','C. Defining a function','D. Iterating through every item in a list'],answer:'B',explanation:'A while loop keeps repeating its body as long as its condition evaluates to True. It is used when you do not know in advance how many times you need to loop.',memory_hook:'While = "keep going while the light is green." As soon as the condition turns false (light goes red), the loop stops.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does this Python code print?\n\nfor i in range(1, 6, 2):\n    print(i)',options:['A. 1 2 3 4 5','B. 1 3 5','C. 2 4 6','D. 1 3 5 7'],answer:'B',explanation:'range(1, 6, 2) starts at 1, stops before 6, and steps by 2. So it produces 1, 3, 5.',memory_hook:'range(start, stop, step) — think of it as a ladder: start on rung 1, step up 2 rungs at a time, stop before rung 6. So you land on 1, 3, 5.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is a 2D array (list of lists) used for?',options:['A. Storing a single sequence of items','B. Storing data in a grid or table structure, like a spreadsheet','C. Sorting items more efficiently','D. Passing multiple values to a function'],answer:'B',explanation:'A 2D array is an array of arrays, allowing data to be stored in rows and columns — useful for grids, game boards, and tabular data.',memory_hook:'A 2D array is like a spreadsheet — rows and columns. grid[2][3] means row 2, column 3, just like a map coordinate.'},

  // ─── PAPER 2: Robust Programs ───
  {paper:'p2',topic:'Robust Programs',q:'What is a syntax error?',options:['A. An error caused by incorrect logic producing wrong results','B. An error that occurs when the program crashes during execution','C. An error caused by code that breaks the rules of the programming language','D. An error caused by invalid user input'],answer:'C',explanation:'A syntax error occurs when code does not follow the grammatical rules of the language, like misspelling a keyword or missing a colon in Python.',memory_hook:'Syntax error = grammar mistake. Like writing "I goed to school" in English — you broke the grammar rules. Python won\'t even try to run it.'},
  {paper:'p2',topic:'Robust Programs',q:'What is a logic error?',options:['A. Code that does not follow language syntax rules','B. A program that crashes mid-execution','C. Code that runs without crashing but produces incorrect results','D. An error caused by dividing by zero'],answer:'C',explanation:'A logic error means the code is syntactically correct and runs without crashing, but the algorithm is wrong so the output is incorrect.',memory_hook:'Logic error = the program lies to you. It runs perfectly, gives you an answer — but it\'s the wrong answer. Like a calculator that always adds 1 extra.'},
  {paper:'p2',topic:'Robust Programs',q:'What is a runtime error?',options:['A. An error in the program\'s logic that produces wrong results','B. An error that causes the program to crash during execution','C. An error caused by incorrect indentation','D. An error that prevents the code from being compiled'],answer:'B',explanation:'A runtime error (or exception) occurs while the program is running — for example, dividing by zero or trying to access a list index that does not exist.',memory_hook:'Runtime error = the program starts fine but crashes mid-run. Like a car that starts but breaks down on the motorway — the problem only shows up in use.'},
  {paper:'p2',topic:'Robust Programs',q:'What is the purpose of testing a program with boundary data?',options:['A. To check the program handles typical, expected inputs','B. To check the program behaves correctly at the edges of acceptable input ranges','C. To check the program rejects completely wrong input types','D. To measure how fast the program runs'],answer:'B',explanation:'Boundary data tests the program at the exact limits of the valid range (e.g. if valid input is 1-10, boundary data would be 1 and 10). These are common failure points.',memory_hook:'Boundary data = testing the fences. You\'re not testing the middle of the field — you\'re checking whether the fence at each edge is solid.'},
  {paper:'p2',topic:'Robust Programs',q:'What does it mean to maintain code?',options:['A. To run the program regularly to check it works','B. To update and improve the code after it has been deployed','C. To back up the source code to prevent loss','D. To compile the code before distribution'],answer:'B',explanation:'Maintenance involves fixing bugs found after release, adapting the program to new requirements, and improving performance or readability over time.',memory_hook:'Code maintenance is like servicing a car — even after it\'s built and working, it needs regular fixes and updates to keep it running well.'},
  {paper:'p2',topic:'Robust Programs',q:'Why should a programmer use meaningful variable names?',options:['A. It makes the program run faster','B. It makes the code easier to read, understand and maintain','C. It reduces the file size of the program','D. It prevents syntax errors'],answer:'B',explanation:'Meaningful variable names (like totalScore rather than x) make code self-documenting, helping other programmers (and your future self) understand what the code does.',memory_hook:'Would you rather read a recipe that says "add x to y" or "add flour to butter"? Meaningful names make code readable without a decoder ring.'},
  {paper:'p2',topic:'Robust Programs',q:'What is the purpose of comments in code?',options:['A. To make the program run in a different order','B. To explain what the code does, making it easier to understand and maintain','C. To prevent certain lines from running during testing','D. To define variables'],answer:'B',explanation:'Comments are lines of text ignored by the interpreter/compiler that explain what the code does, who wrote it, or why certain decisions were made.',memory_hook:'Comments are notes to your future self (and teammates). When you look at your code in 6 months, comments remind you what you were thinking.'},

  // ─── PAPER 2: Boolean Logic ───
  {paper:'p2',topic:'Boolean Logic',q:'What is the truth table output for A AND B when A=1, B=0?',options:['A. 1','B. 0','C. Depends on other inputs','D. Error'],answer:'B',explanation:'AND outputs 1 only when both inputs are 1. Since B=0, the output is 0 regardless of A.',memory_hook:'AND = both or nothing. One person standing down (0) means the whole AND gate gives 0.'},
  {paper:'p2',topic:'Boolean Logic',q:'What is the output of NOT(True AND False)?',options:['A. True','B. False','C. 0','D. Error'],answer:'A',explanation:'True AND False = False. NOT(False) = True.',memory_hook:'Work inside out: AND first (True AND False = False), then NOT flips it (NOT False = True). Brackets first, like in maths.'},
  {paper:'p2',topic:'Boolean Logic',q:'Which logic gate outputs 1 only when its two inputs are different?',options:['A. AND','B. OR','C. NOT','D. XOR'],answer:'D',explanation:'XOR (exclusive OR) outputs 1 when inputs differ: 0 XOR 1 = 1, 1 XOR 0 = 1, but 0 XOR 0 = 0 and 1 XOR 1 = 0.',memory_hook:'XOR = "one or the other but not both." It\'s the picky gate — it wants exactly one 1, not two.'},
  {paper:'p2',topic:'Boolean Logic',q:'A Boolean expression is: NOT A OR B. What is the output when A=1 and B=0?',options:['A. True','B. False','C. 1','D. Both B and C are correct'],answer:'B',explanation:'NOT A = NOT 1 = 0. Then 0 OR 0 = 0 (False).',memory_hook:'Step by step: flip A first (NOT 1 = 0), then OR with B (0 OR 0 = 0). Order of operations matters in Boolean logic just like in maths.'},

  // ─── PAPER 2: Programming Languages & IDEs ───
  {paper:'p2',topic:'Programming Languages',q:'What is the difference between high-level and low-level programming languages?',options:['A. High-level languages are closer to machine code; low-level are closer to English','B. High-level languages are closer to human language; low-level are closer to machine code','C. High-level languages run faster than low-level languages','D. Low-level languages can only run on specific operating systems'],answer:'B',explanation:'High-level languages (Python, Java) use English-like syntax, making them easier to write and understand. Low-level languages (Assembly, machine code) are closer to what the CPU actually processes.',memory_hook:'High-level = high up, near humans. Low-level = low down, near the machine. Python is up here with us; machine code is down there with the CPU.'},
  {paper:'p2',topic:'Programming Languages',q:'What is machine code?',options:['A. Code written in Python or Java','B. Instructions written directly in binary that the CPU can execute without translation','C. A type of pseudocode used in exams','D. Assembly language instructions'],answer:'B',explanation:'Machine code consists of binary instructions that the CPU executes directly. All other programming languages must ultimately be translated into machine code.',memory_hook:'Machine code = the CPU\'s native language. It\'s all 1s and 0s — humans find it unreadable, but it\'s the only thing the CPU actually understands.'},
  {paper:'p2',topic:'Programming Languages',q:'What is an IDE (Integrated Development Environment)?',options:['A. A type of programming language','B. Software that provides tools for writing, testing and debugging code in one place','C. A hardware device used for coding','D. A method of compiling code'],answer:'B',explanation:'An IDE combines a code editor, debugger, compiler/interpreter and other tools in a single application, making the development process more efficient.',memory_hook:'IDE = programmer\'s Swiss Army knife. Instead of switching between separate tools, everything you need (write, run, debug) is in one place.'},
  {paper:'p2',topic:'Programming Languages',q:'What does a debugger in an IDE allow you to do?',options:['A. Automatically fix all errors in your code','B. Step through code line by line and inspect variable values to find errors','C. Convert your code to a different programming language','D. Compress your code files for distribution'],answer:'B',explanation:'A debugger lets you pause program execution, step through code one line at a time, and inspect the current value of variables to identify where bugs occur.',memory_hook:'A debugger is like slow-motion replay — you pause the game (program), rewind, and watch frame by frame to see exactly where it went wrong.'},
  {paper:'p2',topic:'Programming Languages',q:'What is the purpose of a translator in computing?',options:['A. To convert data between different file formats','B. To convert source code written in a programming language into machine code','C. To send data between different network protocols','D. To compress files for storage'],answer:'B',explanation:'Translators (compilers, interpreters, assemblers) convert human-written source code into machine code that the CPU can execute.',memory_hook:'A translator is a language interpreter — it reads your Python/Java etc. and converts it into the binary language the CPU speaks.'},
  {paper:'p2',topic:'Programming Languages',q:'What is assembly language?',options:['A. A high-level language similar to Python','B. A low-level language that uses short mnemonic codes representing machine code instructions','C. The language used to write operating systems only','D. A scripting language used for web development'],answer:'B',explanation:'Assembly language uses short mnemonics (like MOV, ADD, JMP) that correspond directly to machine code instructions. It is much easier to read than binary but still very close to the hardware.',memory_hook:'Assembly = machine code with human-readable labels. ADD instead of 00100011. Still complex, but at least you can read the words.'},

  // ─── PAPER 2: Additional Algorithms ───
  {paper:'p2',topic:'Algorithms',q:'What is the purpose of pseudocode?',options:['A. To write code that runs directly on a computer','B. To plan algorithms in a human-readable format without worrying about syntax','C. To document a completed program','D. To test code without a compiler'],answer:'B',explanation:'Pseudocode describes an algorithm\'s logic in plain language, letting you focus on the solution without getting distracted by programming language syntax rules.',memory_hook:'Pseudo = fake. Pseudocode is fake code — it looks like code but isn\'t runnable. You use it to think through the plan before writing real code.'},
  {paper:'p2',topic:'Algorithms',q:'What is the purpose of a subroutine/function in reducing code complexity?',options:['A. It makes the program use less RAM','B. It allows repeated sections of code to be written once and called multiple times','C. It speeds up the compilation process','D. It prevents runtime errors from occurring'],answer:'B',explanation:'Functions let you write code once and call it many times, reducing repetition, making programs shorter, easier to read and easier to maintain.',memory_hook:'Without functions you\'d write the same instructions over and over. Functions are like copy-paste, but smarter — change it once, fixed everywhere.'},
  {paper:'p2',topic:'Algorithms',q:'What does it mean for an algorithm to be efficient?',options:['A. The algorithm is written in fewer lines of code','B. The algorithm solves the problem using the minimum necessary time and memory resources','C. The algorithm uses only built-in functions','D. The algorithm works only on sorted data'],answer:'B',explanation:'An efficient algorithm achieves the correct result while minimising the computational resources (time and memory) required, especially important for large datasets.',memory_hook:'Efficiency = doing more with less. An efficient algorithm is like a fuel-efficient car — it gets you to the same destination but uses less fuel (resources).'},

  // ─── PAPER 2: More Programming ───
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the difference between a local and global variable?',options:['A. Local variables are faster; global variables are slower','B. Local variables exist only within the function they are declared in; global variables are accessible throughout the whole program','C. Global variables can only store numbers; local variables can store any type','D. There is no practical difference'],answer:'B',explanation:'A local variable exists only inside the function where it is created. A global variable is declared outside functions and can be accessed from anywhere in the program.',memory_hook:'Local = local pub (only people in that neighbourhood go). Global = national news (everyone in the country can see it). Same idea with scope.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does the following Python code do?\n\nmy_list = [3, 1, 4, 1, 5]\nmy_list.append(9)',options:['A. Removes 9 from the list','B. Adds 9 to the end of the list','C. Inserts 9 at the beginning of the list','D. Sorts the list and adds 9'],answer:'B',explanation:'The append() method adds the specified value to the end of a list in Python.',memory_hook:'append() = staple something to the end. Like adding a page to the end of a document. The list grows by one item at its tail.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the index of the first element in a Python list?',options:['A. 1','B. 0','C. -1','D. It depends on the list'],answer:'B',explanation:'Python (like most programming languages) uses zero-based indexing, so the first element is at index 0, the second at index 1, and so on.',memory_hook:'Computers start counting at 0, not 1. So list[0] is the first item. Confusing at first, but it\'s always zero-based in Python — remember it!'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does this Python code output?\n\nwords = ["cat", "dog", "fish"]\nprint(words[1])',options:['A. cat','B. dog','C. fish','D. 1'],answer:'B',explanation:'words[1] accesses index 1, which is the second element "dog" (remembering that index 0 is "cat").',memory_hook:'Index 0 = cat, index 1 = dog, index 2 = fish. It\'s like a numbered hotel room — room 0 is the first, room 1 is the second.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is a parameter in a function?',options:['A. The name given to a function','B. A variable that receives a value passed into a function when it is called','C. The value returned by a function','D. A comment describing what a function does'],answer:'B',explanation:'A parameter is a variable listed in a function\'s definition that receives the value (argument) passed in when the function is called.',memory_hook:'Parameter = the blank on the form. When you call the function, you fill in the blank with your specific value (argument).'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does the return statement do in a function?',options:['A. Stops the program running','B. Sends a value back to the code that called the function','C. Restarts the function from the beginning','D. Prints the result to the screen'],answer:'B',explanation:'The return statement ends function execution and sends a specified value back to wherever the function was called from, making it available for further use.',memory_hook:'return = sending back the result. Like ordering a pizza: you call the shop (function), they make it and return it to you (return value).'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is the purpose of the MOD (%) operator?',options:['A. To multiply two numbers','B. To find the remainder after integer division','C. To convert a number to binary','D. To round a number to the nearest integer'],answer:'B',explanation:'The modulo operator returns the remainder after dividing one number by another. For example, 17 MOD 5 = 2 because 17 ÷ 5 = 3 remainder 2.',memory_hook:'MOD = the leftovers after sharing equally. 17 sweets shared between 5 people: each gets 3, and 2 are left over. MOD gives you the 2.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What does DIV do in OCR ERL?',options:['A. Divides and returns the decimal result','B. Performs integer division, returning only the whole number part','C. Multiplies two integers together','D. Converts a float to an integer'],answer:'B',explanation:'DIV performs integer (whole number) division, discarding any remainder. For example, 17 DIV 5 = 3 (not 3.4).',memory_hook:'DIV = divvy up whole portions only. 17 DIV 5 = 3 because you can only give out 3 complete portions of 5. The leftover 2 is ignored.'},
  {paper:'p2',topic:'Programming Fundamentals',q:'What is string slicing in Python?',options:['A. Splitting a string at every space to create a list','B. Extracting a portion of a string using index positions','C. Removing spaces from the beginning and end of a string','D. Reversing the characters in a string'],answer:'B',explanation:'String slicing extracts a substring using the syntax string[start:end], where start is inclusive and end is exclusive.',memory_hook:'"hello"[1:4] = "ell". Think of the indices as the gaps between letters: 0|h|1|e|2|l|3|l|4|o|5. Slice from gap 1 to gap 4.'},

  // ─── PAPER 2: More Robust/Testing ───
  {paper:'p2',topic:'Robust Programs',q:'What is the difference between white box and black box testing?',options:['A. White box tests the user interface; black box tests the database','B. White box testing uses knowledge of the internal code; black box testing tests inputs and outputs without knowing the code','C. Black box testing is done by the developers; white box by the users','D. There is no difference — both test the same things'],answer:'B',explanation:'White box testing is done with knowledge of the internal code structure. Black box testing only looks at inputs and expected outputs, treating the program as an opaque box.',memory_hook:'White box = glass box — you can see inside (the code). Black box = opaque box — you just poke things in and watch what comes out, no peeking inside.'},
  {paper:'p2',topic:'Robust Programs',q:'What is the purpose of normal test data?',options:['A. To check the program handles inputs outside the valid range','B. To check the program produces correct results for typical valid inputs','C. To test performance under extreme load','D. To check the program rejects invalid data types'],answer:'B',explanation:'Normal data is typical, valid input that the program should process correctly. It checks the basic expected behaviour of the program.',memory_hook:'Normal data = the everyday case. If your program handles real-world typical inputs correctly, it passes the normal data test. Start here before testing edge cases.'},

  // ─── More Paper 1 topics ───
  {paper:'p1',topic:'Binary & Hex',q:'How do you convert the binary number 11001100 to hexadecimal?',options:['A. CC','B. CD','C. DC','D. C3'],answer:'A',explanation:'Split into nibbles: 1100 = C, 1100 = C. So 11001100 in hex is CC.',memory_hook:'Split binary into groups of 4 (nibbles) from the right. Each nibble converts to one hex digit. 1100=12=C, 1100=12=C. Result: CC.'},
  {paper:'p1',topic:'Data Representation',q:'How is a character represented in a computer?',options:['A. As a colour value','B. As a unique binary number using a character encoding standard like ASCII or Unicode','C. As a floating point number','D. As a series of pixels'],answer:'B',explanation:'Characters are represented using encoding systems like ASCII (7-bit) or Unicode (variable width) that map each character to a unique binary number.',memory_hook:'Every character has a secret number. In ASCII, "A" = 65 = 01000001 in binary. The computer just stores the number and the encoding tells it what character it means.'},
  {paper:'p1',topic:'Data Representation',q:'What is the advantage of Unicode over ASCII?',options:['A. Unicode files are smaller than ASCII files','B. Unicode can represent a much larger range of characters including non-Latin scripts','C. Unicode processes faster than ASCII','D. ASCII cannot represent numbers'],answer:'B',explanation:'ASCII only supports 128 characters (basic Latin alphabet, numbers, punctuation). Unicode supports over 1 million characters, including Chinese, Arabic, emoji and more.',memory_hook:'ASCII is a tiny alphabet — only English letters and basic symbols. Unicode is the whole world\'s characters plus emoji. 🌍'},
  {paper:'p1',topic:'Networks',q:'What is bandwidth and how does it affect network performance?',options:['A. The physical length of a network cable','B. The maximum amount of data that can be transmitted over a network in a given time','C. The number of devices connected to a network','D. The encryption strength of a wireless network'],answer:'B',explanation:'Bandwidth is the capacity of a network connection, usually measured in Mbps or Gbps. Higher bandwidth allows more data to flow simultaneously, improving speed.',memory_hook:'Bandwidth is the width of a pipe — a wider pipe carries more water (data) at once. Narrow pipe = slow connection even if pressure (speed) is high.'},
  {paper:'p1',topic:'Networks',q:'What does the TCP/IP protocol suite do?',options:['A. Encrypts all data on a network','B. Defines how data is broken into packets, addressed, transmitted and reassembled across the internet','C. Assigns domain names to IP addresses','D. Controls wireless network access'],answer:'B',explanation:'TCP/IP is the fundamental communication protocol of the internet. TCP handles reliable delivery and reassembly of packets; IP handles addressing and routing.',memory_hook:'TCP/IP is the rulebook for the internet. TCP makes sure all the pages of your book arrive in order; IP makes sure each page has the right address on it.'},
];
